<?xml version="1.0"?>
<!-- Licensed to the Apache Software Foundation (ASF) under one or more contributor 
  license agreements. See the NOTICE file distributed with this work for additional 
  information regarding copyright ownership. The ASF licenses this file to 
  You under the Apache License, Version 2.0 (the "License"); you may not use 
  this file except in compliance with the License. You may obtain a copy of 
  the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required 
  by applicable law or agreed to in writing, software distributed under the 
  License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
  OF ANY KIND, either express or implied. See the License for the specific 
  language governing permissions and limitations under the License. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
         
  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  
  <parent>
    <artifactId>arquillian10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>
  
  <artifactId>arquillian-tomee-tests10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>pom10.0.1-TT.2-SNAPSHOT</packaging>

  <name>TomEE :: Arquillian Adaptors Parent :: Tests10.0.1-TT.2-SNAPSHOT</name>

  <modules>
    <module>arquillian-tomee-webprofile-tests10.0.1-TT.2-SNAPSHOT</module>
    <module>arquillian-tomee-jaxrs-tests10.0.1-TT.2-SNAPSHOT</module>
    <module>arquillian-tomee-jaxws-tests10.0.1-TT.2-SNAPSHOT</module>
    <module>arquillian-tomee-jms-tests10.0.1-TT.2-SNAPSHOT</module>
    <module>arquillian-tomee-config-tests10.0.1-TT.2-SNAPSHOT</module>
  10.0.1-TT.2-SNAPSHOT</modules>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.jboss.shrinkwrap.resolver10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-resolver-impl-maven10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.shrinkwrap.resolver.bom}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>org.apache.httpcomponents10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>httpcore10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.httpcomponents10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>httpcore10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>4.4.1610.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>ziplock10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.jboss.arquillian.junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-junit-container10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.arquillian}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.slf4j10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>slf4j-jdk1410.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.httpcomponents10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>httpclient10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>4.2.210.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.jboss.shrinkwrap.descriptors10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-descriptors-impl-javaee10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.shrinkwrap.descriptor}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap.descriptors10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-descriptors-api-javaee10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.shrinkwrap.descriptor}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-tomee-embedded10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-tomee-remote10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-tomee-webapp-remote10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency> <!-- tomee-embedded needs it + dependencies but tomee-*-remote doesn't need dependencies so to avoid conflicts bringing it back here -->
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- ActiveMQ is optional in openejb-core -->
    <dependency>
      <groupId>org.apache.activemq10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>activemq-ra10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.activemq10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>activemq-broker10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.activemq10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>activemq-jdbc-store10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.activemq10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>activemq-broker10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- for tests with Hibernate -->

    <dependency>
      <groupId>org.hibernate.orm10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>hibernate-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.hibernate.orm}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.hibernate.common10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>hibernate-commons-annotations10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>6.0.4.Final10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>antlr10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>antlr10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>2.7.710.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jandex10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>2.4.5.Final10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.logging10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jboss-logging10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>net.bytebuddy10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>byte-buddy10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.16.110.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <!-- just to get it in the correct order -->
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <classifier>webprofile10.0.1-TT.2-SNAPSHOT</classifier>
      <type>zip10.0.1-TT.2-SNAPSHOT</type>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>zip10.0.1-TT.2-SNAPSHOT</type>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>

  <profiles>

    <profile>
      <id>default10.0.1-TT.2-SNAPSHOT</id>
      <activation>
        <activeByDefault>true10.0.1-TT.2-SNAPSHOT</activeByDefault>
      10.0.1-TT.2-SNAPSHOT</activation>

      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>test-tomee-embedded10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${maven.test.skip}10.0.1-TT.2-SNAPSHOT</skip>
                  <argLine>-javaagent:${settings.localRepository}/org/apache/tomee/openejb-javaagent/${project.version}/openejb-javaagent-${project.version}.jar10.0.1-TT.2-SNAPSHOT</argLine>
                  <systemPropertyVariables>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <arquillian.launch>tomee-embedded10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-embedded10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
            <configuration>
              <skip>true10.0.1-TT.2-SNAPSHOT</skip>
              <parallel>none10.0.1-TT.2-SNAPSHOT</parallel>
              <threadCount>110.0.1-TT.2-SNAPSHOT</threadCount>
              <reuseForks>true10.0.1-TT.2-SNAPSHOT</reuseForks>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>

    <profile>
      <id>all-adapters10.0.1-TT.2-SNAPSHOT</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.gmaven10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>groovy-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>2.1.110.0.1-TT.2-SNAPSHOT</version>
            <executions>
              <execution>
                <id>configure-adapters10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <source>
                    // goal: manage the profile-under-test property
                    // -&gt; set to webprofile use all distributions
                    // -&gt; set to plus use only plus
                    // -&gt; set to plume use only plume
                    def props = project.properties

                    def skip = props['maven.test.skip']

                    props['skip.embedded'] = 'true'
                    props['skip.remote.webprofile'] = 'true'
                    props['skip.remote.plus'] = 'true'
                    props['skip.remote.plume'] = 'true'
                    props['skip.webapp.webprofile'] = 'true'
                    props['skip.webapp.plus'] = 'true'
                    props['skip.webapp.plume'] = 'true'
                    props['skip.remote.microprofile'] = 'true'
                    props['skip.webapp.microprofile'] = 'true'

                    if ("true" != skip) {
                      def minProfile = props['profile-under-test']

                      if ("webprofile" == minProfile) {
                        props['skip.embedded'] = 'false'
                        props['skip.remote.webprofile'] = 'false'
                        props['skip.webapp.webprofile'] = 'false'
                        props['skip.remote.plus'] = 'false'
                        props['skip.webapp.plus'] = 'false'
                        props['skip.remote.plume'] = 'false'
                        props['skip.webapp.plume'] = 'false'
                      } else if ("plus" == minProfile) {
                        props['skip.embedded'] = 'false'
                        props['skip.remote.plus'] = 'false'
                        props['skip.webapp.plus'] = 'false'
                        props['skip.remote.plume'] = props['skip.remote.plume'] ? props['skip.remote.plume'] : 'false'
                        props['skip.webapp.plume'] = props['skip.webapp.plume'] ? props['skip.webapp.plume'] : 'false'
                      }
                    }

                    println("Embedded adapter activated ? " + !Boolean.parseBoolean(props['skip.embedded']))
                    println("Remote webprofile adapter activated ? " +
                        !Boolean.parseBoolean(props['skip.remote.webprofile']))
                    println("Remote plus adapter activated ? " + !Boolean.parseBoolean(props['skip.remote.plus']))
                    println("Remote plume adapter activated ? " + !Boolean.parseBoolean(props['skip.remote.plume']))
                    println("Webapp weprofile adapter activated ? " +
                        !Boolean.parseBoolean(props['skip.webapp.webprofile']))
                    println("Webapp plus adapter activated ? " + !Boolean.parseBoolean(props['skip.webapp.plus']))
                    println("Webapp plume adapter activated ? " + !Boolean.parseBoolean(props['skip.webapp.plume']))
                  10.0.1-TT.2-SNAPSHOT</source>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>

              <execution>
                <id>test-tomee-remote10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${skip.remote.webprofile}10.0.1-TT.2-SNAPSHOT</skip>
                  <systemPropertyVariables>
                    <openejb.arquillian.debug>true10.0.1-TT.2-SNAPSHOT</openejb.arquillian.debug>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <tomee.classifier>webprofile10.0.1-TT.2-SNAPSHOT</tomee.classifier>
                    <arquillian.launch>tomee-remote10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-remote10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>test-tomee-remote-secpol10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${skip.remote.webprofile}10.0.1-TT.2-SNAPSHOT</skip>
                  <systemPropertyVariables>
                    <openejb.arquillian.debug>true10.0.1-TT.2-SNAPSHOT</openejb.arquillian.debug>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <tomee.classifier>webprofile10.0.1-TT.2-SNAPSHOT</tomee.classifier>
                    <arquillian.launch>tomee-remote-secpol10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-remote10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>test-tomee-embedded10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${skip.embedded}10.0.1-TT.2-SNAPSHOT</skip>
                  <argLine>-javaagent:${settings.localRepository}/org/apache/tomee/openejb-javaagent/${project.version}/openejb-javaagent-${project.version}.jar10.0.1-TT.2-SNAPSHOT</argLine>
                  <systemPropertyVariables>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <arquillian.launch>tomee-embedded10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-embedded10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>test-tomee-remote-plume10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${skip.remote.plume}10.0.1-TT.2-SNAPSHOT</skip>
                  <systemPropertyVariables>
                    <openejb.arquillian.debug>true10.0.1-TT.2-SNAPSHOT</openejb.arquillian.debug>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <tomee.classifier>plume10.0.1-TT.2-SNAPSHOT</tomee.classifier>
                    <arquillian.launch>tomee-remote10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-remote10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                  <excludes>
                    <exclude>**/AppComposerTest.java10.0.1-TT.2-SNAPSHOT</exclude>
                  10.0.1-TT.2-SNAPSHOT</excludes>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>test-tomee-remote-plus10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${skip.remote.plus}10.0.1-TT.2-SNAPSHOT</skip>
                  <systemPropertyVariables>
                    <openejb.arquillian.debug>true10.0.1-TT.2-SNAPSHOT</openejb.arquillian.debug>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <tomee.classifier>plus10.0.1-TT.2-SNAPSHOT</tomee.classifier>
                    <arquillian.launch>tomee-remote10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-remote10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>test-tomee-remote-microprofile10.0.1-TT.2-SNAPSHOT</id>
                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <skip>${skip.remote.microprofile}10.0.1-TT.2-SNAPSHOT</skip>
                  <systemPropertyVariables>
                    <openejb.arquillian.debug>true10.0.1-TT.2-SNAPSHOT</openejb.arquillian.debug>
                    <tomee.version>${project.version}10.0.1-TT.2-SNAPSHOT</tomee.version>
                    <tomee.classifier>microprofile10.0.1-TT.2-SNAPSHOT</tomee.classifier>
                    <arquillian.launch>tomee-remote10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <openejb.arquillian.adapter>tomee-remote10.0.1-TT.2-SNAPSHOT</openejb.arquillian.adapter>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
            <configuration>
              <skip>true10.0.1-TT.2-SNAPSHOT</skip>
              <parallel>none10.0.1-TT.2-SNAPSHOT</parallel>
              <threadCount>110.0.1-TT.2-SNAPSHOT</threadCount>
              <reuseForks>true10.0.1-TT.2-SNAPSHOT</reuseForks>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>

    <profile>
      <!--
      Added to make it easy to quickly verify if something "should" work
      -->
      <id>glassfish-embedded10.0.1-TT.2-SNAPSHOT</id>
      <properties>
        <version.glassfish>3.1.2.210.0.1-TT.2-SNAPSHOT</version.glassfish>
        <version.arquillian.glassfish.embedded>1.0.210.0.1-TT.2-SNAPSHOT</version.arquillian.glassfish.embedded>
        <version.mockito>1.9.010.0.1-TT.2-SNAPSHOT</version.mockito>
        <version.maven.embedded.glassfish.plugin>3.1.110.0.1-TT.2-SNAPSHOT</version.maven.embedded.glassfish.plugin>
        <version.maven.war.plugin>2.1.110.0.1-TT.2-SNAPSHOT</version.maven.war.plugin>
        <version.maven.compiler.plugin>2.3.210.0.1-TT.2-SNAPSHOT</version.maven.compiler.plugin>
        <version.maven.failsafe.plugin>2.1110.0.1-TT.2-SNAPSHOT</version.maven.failsafe.plugin>
        <project.build.sourceEncoding>UTF-810.0.1-TT.2-SNAPSHOT</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-810.0.1-TT.2-SNAPSHOT</project.reporting.outputEncoding>
      10.0.1-TT.2-SNAPSHOT</properties>
      <dependencies>
        <dependency>
          <groupId>org.jboss.arquillian.junit10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>arquillian-junit-container10.0.1-TT.2-SNAPSHOT</artifactId>
          <version>${version.arquillian}10.0.1-TT.2-SNAPSHOT</version>
          <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
          <groupId>org.glassfish.main.extras10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>glassfish-embedded-all10.0.1-TT.2-SNAPSHOT</artifactId>
          <version>${version.glassfish}10.0.1-TT.2-SNAPSHOT</version>
          <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
          <groupId>org.jboss.arquillian.container10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>arquillian-glassfish-embedded-3.110.0.1-TT.2-SNAPSHOT</artifactId>
          <version>${version.arquillian.glassfish.embedded}10.0.1-TT.2-SNAPSHOT</version>
          <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
      10.0.1-TT.2-SNAPSHOT</dependencies>
    10.0.1-TT.2-SNAPSHOT</profile>
  10.0.1-TT.2-SNAPSHOT</profiles>

  <properties>
    <profile-under-test>webprofile10.0.1-TT.2-SNAPSHOT</profile-under-test>
  10.0.1-TT.2-SNAPSHOT</properties>
10.0.1-TT.2-SNAPSHOT</project>
