<?xml version="1.0" encoding="UTF-8"?>
<!--
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>tomee10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.1-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
    <relativePath>../pom.xml10.0.1-TT.2-SNAPSHOT</relativePath>
  10.0.1-TT.2-SNAPSHOT</parent>

  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <artifactId>tomee-deb10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>jar10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: TomEE :: Debian Package Builder10.0.1-TT.2-SNAPSHOT</name>

  <properties>
    <distribution.workdir>${project.build.directory}/work-dir10.0.1-TT.2-SNAPSHOT</distribution.workdir>
  10.0.1-TT.2-SNAPSHOT</properties>

  <dependencies>
    <!-- Dependencies used by builder logic. -->
    <dependency>
      <groupId>org.apache.maven10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>maven-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>3.2.110.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.codehaus.groovy10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>groovy-all10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-compress10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-lang310.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>commons-io10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-io10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>commons-codec10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-codec10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- We need to be sure the ZIP files are built before the debian package. -->
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>pom10.0.1-TT.2-SNAPSHOT</type>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- We use resources from these guys below. -->
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf-rs10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-hsql10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>copy-tomee-zip10.0.1-TT.2-SNAPSHOT</id>
            <phase>prepare-package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
                  <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
                  <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
                  <classifier>plus10.0.1-TT.2-SNAPSHOT</classifier>
                  <type>zip10.0.1-TT.2-SNAPSHOT</type>
                  <outputDirectory>${distribution.workdir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                  <destFileName>tomee-plus.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                10.0.1-TT.2-SNAPSHOT</artifactItem>
                <artifactItem>
                  <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
                  <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
                  <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
                  <classifier>webprofile10.0.1-TT.2-SNAPSHOT</classifier>
                  <type>zip10.0.1-TT.2-SNAPSHOT</type>
                  <outputDirectory>${distribution.workdir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                  <destFileName>tomee-webprofile.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                10.0.1-TT.2-SNAPSHOT</artifactItem>
                <artifactItem>
                  <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
                  <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
                  <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
                  <classifier>plume10.0.1-TT.2-SNAPSHOT</classifier>
                  <type>zip10.0.1-TT.2-SNAPSHOT</type>
                  <outputDirectory>${distribution.workdir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                  <destFileName>tomee-plume.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                10.0.1-TT.2-SNAPSHOT</artifactItem>
              10.0.1-TT.2-SNAPSHOT</artifactItems>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.codehaus.gmaven10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>groovy-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <configuration>
          <classpathScope>runtime10.0.1-TT.2-SNAPSHOT</classpathScope>
          <scriptpath>
            <path>${project.basedir}/src/main/groovy10.0.1-TT.2-SNAPSHOT</path>
          10.0.1-TT.2-SNAPSHOT</scriptpath>
          <defaults>
            <testSectionsFile>${project.basedir}/sections.properties10.0.1-TT.2-SNAPSHOT</testSectionsFile>
            <logOutputDirectory>${project.build.directory}/logs10.0.1-TT.2-SNAPSHOT</logOutputDirectory>
            <backupLogs>true10.0.1-TT.2-SNAPSHOT</backupLogs>
          10.0.1-TT.2-SNAPSHOT</defaults>
        10.0.1-TT.2-SNAPSHOT</configuration>
        <executions>
          <execution>
            <id>build-distribution10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <source>
                new org.apache.tomee.deb.PackageBuilder(project).createPackage()
              10.0.1-TT.2-SNAPSHOT</source>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.codehaus.mojo10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>build-helper-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>attach-artifacts10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>attach-artifact10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <artifacts>
                <artifact>
                  <file>${project.build.directory}/work-dir/apache-tomee-plus.deb10.0.1-TT.2-SNAPSHOT</file>
                  <type>deb10.0.1-TT.2-SNAPSHOT</type>
                  <classifier>plus10.0.1-TT.2-SNAPSHOT</classifier>
                10.0.1-TT.2-SNAPSHOT</artifact>
                <artifact>
                  <file>${project.build.directory}/work-dir/apache-tomee-webprofile.deb
                  10.0.1-TT.2-SNAPSHOT</file>
                  <type>deb10.0.1-TT.2-SNAPSHOT</type>
                  <classifier>webprofile10.0.1-TT.2-SNAPSHOT</classifier>
                10.0.1-TT.2-SNAPSHOT</artifact>
                <artifact>
                  <file>${project.build.directory}/work-dir/apache-tomee-plume.deb
                  10.0.1-TT.2-SNAPSHOT</file>
                  <type>deb10.0.1-TT.2-SNAPSHOT</type>
                  <classifier>plume10.0.1-TT.2-SNAPSHOT</classifier>
                10.0.1-TT.2-SNAPSHOT</artifact>
                <artifact>
                  <file>${project.build.directory}/work-dir/apache-libtomee-plume-java.deb
                  10.0.1-TT.2-SNAPSHOT</file>
                  <type>deb10.0.1-TT.2-SNAPSHOT</type>
                  <classifier>lib-plume10.0.1-TT.2-SNAPSHOT</classifier>
                10.0.1-TT.2-SNAPSHOT</artifact>
                <artifact>
                  <file>${project.build.directory}/work-dir/apache-libtomee-plus-java.deb
                  10.0.1-TT.2-SNAPSHOT</file>
                  <type>deb10.0.1-TT.2-SNAPSHOT</type>
                  <classifier>lib-plus10.0.1-TT.2-SNAPSHOT</classifier>
                10.0.1-TT.2-SNAPSHOT</artifact>
                <artifact>
                  <file>${project.build.directory}/work-dir/apache-libtomee-webprofile-java.deb
                  10.0.1-TT.2-SNAPSHOT</file>
                  <type>deb10.0.1-TT.2-SNAPSHOT</type>
                  <classifier>lib-webprofile10.0.1-TT.2-SNAPSHOT</classifier>
                10.0.1-TT.2-SNAPSHOT</artifact>
              10.0.1-TT.2-SNAPSHOT</artifacts>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>
10.0.1-TT.2-SNAPSHOT</project>
