<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>tck10.0.1-TT.2-SNAPSHOT</artifactId>
        <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
        <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</parent>

    <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
    <artifactId>jsonp-signature-test10.0.1-TT.2-SNAPSHOT</artifactId>
    <name>TomEE :: TCK :: JSON-P Signature Tests10.0.1-TT.2-SNAPSHOT</name>

    <dependencies>
        <dependency>
            <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</dependency>

        <dependency>
            <groupId>jakarta.json10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.json-tck-tests10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${jsonp-tck.version}10.0.1-TT.2-SNAPSHOT</version>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>

        <dependency>
            <groupId>org.apache.johnzon10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>johnzon-core10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</dependency>

        <dependency>
            <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>openwebbeans-se10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${version.openwebbeans}10.0.1-TT.2-SNAPSHOT</version>
        10.0.1-TT.2-SNAPSHOT</dependency>

        <dependency>
            <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>openwebbeans-impl10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</dependency>

        <dependency>
            <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>openwebbeans-spi10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</dependency>

        <dependency>
            <groupId>org.netbeans.tools10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>sigtest-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>1.610.0.1-TT.2-SNAPSHOT</version>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
    10.0.1-TT.2-SNAPSHOT</dependencies>

    <profiles>
        <profile>
            <id>tck-jsonp10.0.1-TT.2-SNAPSHOT</id>
            <build>
                <testResources>
                    <testResource>
                        <directory>src/test/resources10.0.1-TT.2-SNAPSHOT</directory>
                        <filtering>true10.0.1-TT.2-SNAPSHOT</filtering>
                    10.0.1-TT.2-SNAPSHOT</testResource>
                10.0.1-TT.2-SNAPSHOT</testResources>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <executions>
                            <execution>
                                <id>copy10.0.1-TT.2-SNAPSHOT</id>
                                <phase>generate-test-resources10.0.1-TT.2-SNAPSHOT</phase>
                                <goals>
                                    <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                                10.0.1-TT.2-SNAPSHOT</goals>

                                <configuration>
                                    <artifactItems>
                                        <artifactItem>
                                            <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
                                            <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
                                            <version>${version.jakartaee-api}10.0.1-TT.2-SNAPSHOT</version>
                                            <type>jar10.0.1-TT.2-SNAPSHOT</type>
                                            <overWrite>true10.0.1-TT.2-SNAPSHOT</overWrite>
                                            <outputDirectory>${project.build.directory}/signaturedirectory
                                            10.0.1-TT.2-SNAPSHOT</outputDirectory>
                                            <destFileName>jakartaee-api.jar10.0.1-TT.2-SNAPSHOT</destFileName>
                                        10.0.1-TT.2-SNAPSHOT</artifactItem>
                                    10.0.1-TT.2-SNAPSHOT</artifactItems>
                                10.0.1-TT.2-SNAPSHOT</configuration>
                            10.0.1-TT.2-SNAPSHOT</execution>
                        10.0.1-TT.2-SNAPSHOT</executions>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-antrun-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <version>3.1.010.0.1-TT.2-SNAPSHOT</version>
                        <executions>
                            <execution>
                                <id>setup-project10.0.1-TT.2-SNAPSHOT</id>
                                <phase>test-compile10.0.1-TT.2-SNAPSHOT</phase>
                                <goals>
                                    <goal>run10.0.1-TT.2-SNAPSHOT</goal>
                                10.0.1-TT.2-SNAPSHOT</goals>
                                <configuration>
                                    <target name="remove-jakarta-json-bind">
                                        <echo>Removing jakarta.json.bind classes from the jakartaee-api.jar (we cannot
                                            exclude that package them from the sigtests).
                                        10.0.1-TT.2-SNAPSHOT</echo>

                                        <property name="library.dir" value="signaturedirectory" />
                                        <property name="library.file" value="jakartaee-api.jar" />
                                        <property name="library.path" value="${project.build.directory}/${library.dir}/${library.file}" />
                                        <property name="library.path.new" value="${project.build.directory}/${library.dir}/new-${library.file}" />

                                        <jar destfile="${library.path.new}">
                                            <zipfileset src="${library.path}" excludes="jakarta/json/bind/**" />
                                        10.0.1-TT.2-SNAPSHOT</jar>

                                        <delete file="${library.path}" />
                                        <move file="${library.path.new}" tofile="${library.path}" />

                                    10.0.1-TT.2-SNAPSHOT</target>
                                10.0.1-TT.2-SNAPSHOT</configuration>
                            10.0.1-TT.2-SNAPSHOT</execution>
                        10.0.1-TT.2-SNAPSHOT</executions>

                    10.0.1-TT.2-SNAPSHOT</plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <version>${surefire.version}10.0.1-TT.2-SNAPSHOT</version>
                        <configuration>
                            <reuseForks>false10.0.1-TT.2-SNAPSHOT</reuseForks>
                            <forkCount>110.0.1-TT.2-SNAPSHOT</forkCount>
                            <systemProperties>
                                <jimage.dir>${project.build.directory}/jimage10.0.1-TT.2-SNAPSHOT</jimage.dir>
                                <signature.sigTestClasspath>
                                    ${project.build.directory}/signaturedirectory/jakartaee-api.jar:${project.build.directory}/jimage/java.base:${project.build.directory}/jimage/java.rmi:${project.build.directory}/jimage/java.sql:${project.build.directory}/jimage/java.naming
                                10.0.1-TT.2-SNAPSHOT</signature.sigTestClasspath>
                            10.0.1-TT.2-SNAPSHOT</systemProperties>
                            <dependenciesToScan>
                                <dependency>jakarta.json:jakarta.json-tck-tests10.0.1-TT.2-SNAPSHOT</dependency>
                            10.0.1-TT.2-SNAPSHOT</dependenciesToScan>
                            <includes>
                                <include>**/JSONPSigTest10.0.1-TT.2-SNAPSHOT</include>
                            10.0.1-TT.2-SNAPSHOT</includes>
                        10.0.1-TT.2-SNAPSHOT</configuration>

                    10.0.1-TT.2-SNAPSHOT</plugin>
                10.0.1-TT.2-SNAPSHOT</plugins>
            10.0.1-TT.2-SNAPSHOT</build>
        10.0.1-TT.2-SNAPSHOT</profile>
    10.0.1-TT.2-SNAPSHOT</profiles>
10.0.1-TT.2-SNAPSHOT</project>