<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!-- $Rev: 600338 $ $Date: 2007-12-02 09:08:04 -0800 (Sun, 02 Dec 2007) $ -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <parent>
    <artifactId>tomee10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>

  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>jar10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: TomEE :: Apache TomEE10.0.1-TT.2-SNAPSHOT</name>

  <properties>
    <tomee.build.name>${project.groupId}.tomee.tomee10.0.1-TT.2-SNAPSHOT</tomee.build.name>
    <webprofile.work-dir>${project.build.directory}/webprofile-work-dir10.0.1-TT.2-SNAPSHOT</webprofile.work-dir>
    <plus.work-dir>${project.build.directory}/plus-work-dir10.0.1-TT.2-SNAPSHOT</plus.work-dir>
    <plume.work-dir>${project.build.directory}/plume-work-dir10.0.1-TT.2-SNAPSHOT</plume.work-dir>
    <microprofile.work-dir>${project.build.directory}/microprofile-work-dir10.0.1-TT.2-SNAPSHOT</microprofile.work-dir>
    <jdk.attach.allowAttachSelf>true10.0.1-TT.2-SNAPSHOT</jdk.attach.allowAttachSelf>
  10.0.1-TT.2-SNAPSHOT</properties>

  <dependencies>
    <dependency>
      <groupId>org.codehaus.groovy10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>groovy-all10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.2.610.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-impl-base10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.2.610.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>jline10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jline10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.ant10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>ant-nodeps10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <artifactId>commons-lang310.0.1-TT.2-SNAPSHOT</artifactId>
      <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
      <type>zip10.0.1-TT.2-SNAPSHOT</type>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-common10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>jar10.0.1-TT.2-SNAPSHOT</type>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency> <!-- to be sure to have it -->
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-webapp10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>war10.0.1-TT.2-SNAPSHOT</type>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency> <!-- to be sure to have it -->
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-plus-webapp10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>war10.0.1-TT.2-SNAPSHOT</type>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency> <!-- to be sure to have it -->
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-plume-webapp10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>war10.0.1-TT.2-SNAPSHOT</type>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency> <!-- to be sure to have it -->
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-microprofile-webapp10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>war10.0.1-TT.2-SNAPSHOT</type>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- needed for EJBContainer impl so scope compile -->
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-util10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-client10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>jar10.0.1-TT.2-SNAPSHOT</type>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-javaagent10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>jar10.0.1-TT.2-SNAPSHOT</type>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>




    <!-- needed to compile in intellij for tomcat patches -->
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- needed for BOM generation -->
    <dependency>
      <groupId>org.projectlombok10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>lombok10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.18.3610.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources10.0.1-TT.2-SNAPSHOT</directory>
        <filtering>true10.0.1-TT.2-SNAPSHOT</filtering>
      10.0.1-TT.2-SNAPSHOT</resource>
      <resource>
        <directory>src/main/resources10.0.1-TT.2-SNAPSHOT</directory>
        <filtering>false10.0.1-TT.2-SNAPSHOT</filtering>
      10.0.1-TT.2-SNAPSHOT</resource>
    10.0.1-TT.2-SNAPSHOT</resources>
    <testResources>
      <testResource>
        <directory>src/test/resources10.0.1-TT.2-SNAPSHOT</directory>
        <filtering>true10.0.1-TT.2-SNAPSHOT</filtering>
      10.0.1-TT.2-SNAPSHOT</testResource>
    10.0.1-TT.2-SNAPSHOT</testResources>
  10.0.1-TT.2-SNAPSHOT</build>

  <profiles>
    <profile>
      <id>all10.0.1-TT.2-SNAPSHOT</id>
      <activation>
        <activeByDefault>true10.0.1-TT.2-SNAPSHOT</activeByDefault>
      10.0.1-TT.2-SNAPSHOT</activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-jar-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <configuration>
              <includes>
                <include>**/RemoteTomEEEJBContainer*.class10.0.1-TT.2-SNAPSHOT</include>
                <include>**/META-INF/services/jakarta.ejb.spi.EJBContainerProvider10.0.1-TT.2-SNAPSHOT</include>
              10.0.1-TT.2-SNAPSHOT</includes>
              <archive combine.children="append">
                <manifestEntries>
                  <Automatic-Module-Name>${tomee.build.name}10.0.1-TT.2-SNAPSHOT</Automatic-Module-Name>
                10.0.1-TT.2-SNAPSHOT</manifestEntries>
              10.0.1-TT.2-SNAPSHOT</archive>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-failsafe-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <dependencies>
              <dependency>
                <groupId>org.apache.tomee.bom10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>jaxb-runtime10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>8.0.1010.0.1-TT.2-SNAPSHOT</version> <!-- required for the plugin -->
                <type>pom10.0.1-TT.2-SNAPSHOT</type>
              10.0.1-TT.2-SNAPSHOT</dependency>
            10.0.1-TT.2-SNAPSHOT</dependencies>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test10.0.1-TT.2-SNAPSHOT</goal>
                  <goal>verify10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-resources-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <configuration>
              <nonFilteredFileExtensions>
                <nonFilteredFileExtension>exe10.0.1-TT.2-SNAPSHOT</nonFilteredFileExtension>
              10.0.1-TT.2-SNAPSHOT</nonFilteredFileExtensions>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <id>filter-resources10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>resources10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>copy-tomcat-for-webprofile10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
                      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
                      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <outputDirectory>${webprofile.work-dir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                      <destFileName>apache-tomcat-${tomcat.version}.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                    10.0.1-TT.2-SNAPSHOT</artifactItem>
                  10.0.1-TT.2-SNAPSHOT</artifactItems>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>copy-tomcat-for-plus10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
                      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
                      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <outputDirectory>${plus.work-dir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                      <destFileName>apache-tomcat-${tomcat.version}.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                    10.0.1-TT.2-SNAPSHOT</artifactItem>
                  10.0.1-TT.2-SNAPSHOT</artifactItems>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>copy-tomcat-for-plume10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
                      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
                      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <outputDirectory>${plume.work-dir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                      <destFileName>apache-tomcat-${tomcat.version}.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                    10.0.1-TT.2-SNAPSHOT</artifactItem>
                  10.0.1-TT.2-SNAPSHOT</artifactItems>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>copy-tomcat-for-microprofile10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
                      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
                      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <outputDirectory>${microprofile.work-dir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                      <destFileName>apache-tomcat-${tomcat.version}.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                    10.0.1-TT.2-SNAPSHOT</artifactItem>
                  10.0.1-TT.2-SNAPSHOT</artifactItems>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>

          <plugin>
            <groupId>org.codehaus.gmaven10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>groovy-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>2.1.110.0.1-TT.2-SNAPSHOT</version>
            <dependencies>
              <dependency>
                <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${version.jakartaee-api}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>org.apache.tomee.bom10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>jaxb-runtime10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
                <type>pom10.0.1-TT.2-SNAPSHOT</type>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>openejb-jpa-integration10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>org.apache.xbean10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>xbean-asm9-shaded10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${version.xbean}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>org.codehaus.groovy10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>groovy-all10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${version.groovy}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
            10.0.1-TT.2-SNAPSHOT</dependencies>
            <configuration>
              <classpathScope>runtime10.0.1-TT.2-SNAPSHOT</classpathScope>
              <scriptpath>
                <path>${project.basedir}/src/main/groovy10.0.1-TT.2-SNAPSHOT</path>
              10.0.1-TT.2-SNAPSHOT</scriptpath>
              <defaults>
                <testSectionsFile>${project.basedir}/sections.properties10.0.1-TT.2-SNAPSHOT</testSectionsFile>
                <logOutputDirectory>${project.build.directory}/logs10.0.1-TT.2-SNAPSHOT</logOutputDirectory>
                <backupLogs>true10.0.1-TT.2-SNAPSHOT</backupLogs>
              10.0.1-TT.2-SNAPSHOT</defaults>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <id>execute-web-profile-installer10.0.1-TT.2-SNAPSHOT</id>
                <phase>prepare-package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <properties>
                    <tomee.workdir>${webprofile.work-dir}10.0.1-TT.2-SNAPSHOT</tomee.workdir>
                    <tomee.webapp>tomee-webapp10.0.1-TT.2-SNAPSHOT</tomee.webapp>
                    <remove.datestamp>${tomee.version}, ${project.version}, ${version.cxf}10.0.1-TT.2-SNAPSHOT</remove.datestamp>
                    <jdk.attach.allowAttachSelf>true10.0.1-TT.2-SNAPSHOT</jdk.attach.allowAttachSelf>
                  10.0.1-TT.2-SNAPSHOT</properties>
                  <source>
                    new commands.SetupCommand(pom: this, log: log, project: project, ant: ant, properties: properties).execute()
                  10.0.1-TT.2-SNAPSHOT</source>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>execute-plus-installer10.0.1-TT.2-SNAPSHOT</id>
                <phase>prepare-package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <properties>
                    <tomee.workdir>${plus.work-dir}10.0.1-TT.2-SNAPSHOT</tomee.workdir>
                    <tomee.webapp>tomee-plus-webapp10.0.1-TT.2-SNAPSHOT</tomee.webapp>
                    <remove.datestamp>${tomee.version}, ${project.version}, ${version.cxf}10.0.1-TT.2-SNAPSHOT</remove.datestamp>
                    <jdk.attach.allowAttachSelf>true10.0.1-TT.2-SNAPSHOT</jdk.attach.allowAttachSelf>
                  10.0.1-TT.2-SNAPSHOT</properties>
                  <source>
                    new commands.SetupCommand(pom: this, log: log, project: project, ant: ant, properties: properties).execute()
                  10.0.1-TT.2-SNAPSHOT</source>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>execute-plume-installer10.0.1-TT.2-SNAPSHOT</id>
                <phase>prepare-package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <properties>
                    <tomee.workdir>${plume.work-dir}10.0.1-TT.2-SNAPSHOT</tomee.workdir>
                    <tomee.webapp>tomee-plume-webapp10.0.1-TT.2-SNAPSHOT</tomee.webapp>
                    <remove.datestamp>${tomee.version}, ${project.version}, ${version.cxf}10.0.1-TT.2-SNAPSHOT</remove.datestamp>
                    <jdk.attach.allowAttachSelf>true10.0.1-TT.2-SNAPSHOT</jdk.attach.allowAttachSelf>
                  10.0.1-TT.2-SNAPSHOT</properties>
                  <source>
                    new commands.SetupCommand(pom: this, log: log, project: project, ant: ant, properties: properties).execute()
                  10.0.1-TT.2-SNAPSHOT</source>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>execute-microprofile-installer10.0.1-TT.2-SNAPSHOT</id>
                <phase>prepare-package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <properties>
                    <tomee.workdir>${microprofile.work-dir}10.0.1-TT.2-SNAPSHOT</tomee.workdir>
                    <tomee.webapp>tomee-microprofile-webapp10.0.1-TT.2-SNAPSHOT</tomee.webapp>
                    <remove.datestamp>${tomee.version}, ${project.version}, ${version.cxf}10.0.1-TT.2-SNAPSHOT</remove.datestamp>
                    <jdk.attach.allowAttachSelf>true10.0.1-TT.2-SNAPSHOT</jdk.attach.allowAttachSelf>
                  10.0.1-TT.2-SNAPSHOT</properties>
                  <source>
                    new commands.SetupCommand(pom: this, log: log, project: project, ant: ant, properties: properties).execute()
                  10.0.1-TT.2-SNAPSHOT</source>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>

          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-assembly-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>webprofile10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <configuration>
                  <descriptors>
                    <descriptor>src/main/assembly/tomee-webprofile.xml10.0.1-TT.2-SNAPSHOT</descriptor>
                  10.0.1-TT.2-SNAPSHOT</descriptors>
                  <attach>false10.0.1-TT.2-SNAPSHOT</attach>
                  <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
                  <finalName>apache-tomee-webprofile-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
                10.0.1-TT.2-SNAPSHOT</configuration>
                <goals>
                  <goal>single10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>plus10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <configuration>
                  <descriptors>
                    <descriptor>src/main/assembly/tomee-plus.xml10.0.1-TT.2-SNAPSHOT</descriptor>
                  10.0.1-TT.2-SNAPSHOT</descriptors>
                  <attach>false10.0.1-TT.2-SNAPSHOT</attach>
                  <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
                  <finalName>apache-tomee-plus-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
                10.0.1-TT.2-SNAPSHOT</configuration>
                <goals>
                  <goal>single10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>plume10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <configuration>
                  <descriptors>
                    <descriptor>src/main/assembly/tomee-plume.xml10.0.1-TT.2-SNAPSHOT</descriptor>
                  10.0.1-TT.2-SNAPSHOT</descriptors>
                  <attach>false10.0.1-TT.2-SNAPSHOT</attach>
                  <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
                  <finalName>apache-tomee-plume-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
                10.0.1-TT.2-SNAPSHOT</configuration>
                <goals>
                  <goal>single10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>microprofile10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <configuration>
                  <descriptors>
                    <descriptor>src/main/assembly/tomee-microprofile.xml10.0.1-TT.2-SNAPSHOT</descriptor>
                  10.0.1-TT.2-SNAPSHOT</descriptors>
                  <attach>false10.0.1-TT.2-SNAPSHOT</attach>
                  <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
                  <finalName>apache-tomee-microprofile-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
                10.0.1-TT.2-SNAPSHOT</configuration>
                <goals>
                  <goal>single10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>

          <plugin>
            <groupId>org.codehaus.mojo10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>build-helper-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>attach-artifacts10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>attach-artifact10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifacts>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-webprofile-${project.version}.zip10.0.1-TT.2-SNAPSHOT</file>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>webprofile10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-webprofile-${project.version}.tar.gz10.0.1-TT.2-SNAPSHOT</file>
                      <type>tar.gz10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>webprofile10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-plus-${project.version}.zip10.0.1-TT.2-SNAPSHOT</file>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>plus10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-plus-${project.version}.tar.gz10.0.1-TT.2-SNAPSHOT</file>
                      <type>tar.gz10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>plus10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-plume-${project.version}.zip10.0.1-TT.2-SNAPSHOT</file>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>plume10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-plume-${project.version}.tar.gz10.0.1-TT.2-SNAPSHOT</file>
                      <type>tar.gz10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>plume10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-microprofile-${project.version}.zip10.0.1-TT.2-SNAPSHOT</file>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>microprofile10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-microprofile-${project.version}.tar.gz10.0.1-TT.2-SNAPSHOT</file>
                      <type>tar.gz10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>microprofile10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                  10.0.1-TT.2-SNAPSHOT</artifacts>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.tomee.patch10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>tomee-patch-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <configuration>
              <select>apache-tomee-(plus|plume|webprofile|microprofile).*\.zip10.0.1-TT.2-SNAPSHOT</select>
              <skipTransform>true10.0.1-TT.2-SNAPSHOT</skipTransform>
              <createTarGz>true10.0.1-TT.2-SNAPSHOT</createTarGz>
              <skips>
                <jars>
                  <bcpkix-jdk15to18-1.80.jar>org.bouncycastle:bcpkix-jdk15to18:jar:1.8010.0.1-TT.2-SNAPSHOT</bcpkix-jdk15to18-1.80.jar>
                  <bcprov-jdk15to18-1.80.jar>org.bouncycastle:bcprov-jdk15to18:jar:1.8010.0.1-TT.2-SNAPSHOT</bcprov-jdk15to18-1.80.jar>
                  <bcutil-jdk15to18-1.80.jar>org.bouncycastle:bcutil-jdk15to18:jar:1.8010.0.1-TT.2-SNAPSHOT</bcutil-jdk15to18-1.80.jar>
                  <!-- Don't modify bootstrap.jar. Current patch plugin 0.10 has an ambiguity adding classes in more than one target jar if the packages are matching -->
                  <bootstrap.jar>bootstrap.jar10.0.1-TT.2-SNAPSHOT</bootstrap.jar>
                10.0.1-TT.2-SNAPSHOT</jars>
              10.0.1-TT.2-SNAPSHOT</skips>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <goals>
                  <goal>run10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.codehaus.mojo10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>exec-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>3.0.010.0.1-TT.2-SNAPSHOT</version>
            <executions>
              <execution>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>java10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
            <configuration>
              <includeProjectDependencies>true10.0.1-TT.2-SNAPSHOT</includeProjectDependencies>
              <includePluginDependencies>false10.0.1-TT.2-SNAPSHOT</includePluginDependencies>
              <classpathScope>test10.0.1-TT.2-SNAPSHOT</classpathScope>
              <mainClass>org.apache.tomee.bootstrap.GenerateBoms10.0.1-TT.2-SNAPSHOT</mainClass>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>
    <profile>
      <id>plume10.0.1-TT.2-SNAPSHOT</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-jar-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <configuration>
              <includes>
                <include>**/RemoteTomEEEJBContainer*.class10.0.1-TT.2-SNAPSHOT</include>
                <include>**/META-INF/services/jakarta.ejb.spi.EJBContainerProvider10.0.1-TT.2-SNAPSHOT</include>
              10.0.1-TT.2-SNAPSHOT</includes>
              <archive combine.children="append">
                <manifestEntries>
                  <Automatic-Module-Name>${tomee.build.name}10.0.1-TT.2-SNAPSHOT</Automatic-Module-Name>
                10.0.1-TT.2-SNAPSHOT</manifestEntries>
              10.0.1-TT.2-SNAPSHOT</archive>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-failsafe-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test10.0.1-TT.2-SNAPSHOT</goal>
                  <goal>verify10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-resources-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <configuration>
              <nonFilteredFileExtensions>
                <nonFilteredFileExtension>exe10.0.1-TT.2-SNAPSHOT</nonFilteredFileExtension>
              10.0.1-TT.2-SNAPSHOT</nonFilteredFileExtensions>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <id>filter-resources10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>resources10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>copy-tomcat-for-plume10.0.1-TT.2-SNAPSHOT</id>
                <phase>process-resources10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
                      <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
                      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <outputDirectory>${plume.work-dir}10.0.1-TT.2-SNAPSHOT</outputDirectory>
                      <destFileName>apache-tomcat-${tomcat.version}.zip10.0.1-TT.2-SNAPSHOT</destFileName>
                    10.0.1-TT.2-SNAPSHOT</artifactItem>
                  10.0.1-TT.2-SNAPSHOT</artifactItems>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>

          <plugin>
            <groupId>org.codehaus.gmaven10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>groovy-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <dependencies>
              <dependency>
                <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${version.jakartaee-api}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>org.apache.tomee.bom10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>jaxb-runtime10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
                <type>pom10.0.1-TT.2-SNAPSHOT</type>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>openejb-jpa-integration10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>org.apache.xbean10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>xbean-asm9-shaded10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${version.xbean}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
              <dependency>
                <groupId>org.codehaus.groovy10.0.1-TT.2-SNAPSHOT</groupId>
                <artifactId>groovy-all10.0.1-TT.2-SNAPSHOT</artifactId>
                <version>${version.groovy}10.0.1-TT.2-SNAPSHOT</version>
              10.0.1-TT.2-SNAPSHOT</dependency>
            10.0.1-TT.2-SNAPSHOT</dependencies>
            <configuration>
              <classpathScope>runtime10.0.1-TT.2-SNAPSHOT</classpathScope>
              <scriptpath>
                <path>${project.basedir}/src/main/groovy10.0.1-TT.2-SNAPSHOT</path>
              10.0.1-TT.2-SNAPSHOT</scriptpath>
              <defaults>
                <testSectionsFile>${project.basedir}/sections.properties10.0.1-TT.2-SNAPSHOT</testSectionsFile>
                <logOutputDirectory>${project.build.directory}/logs10.0.1-TT.2-SNAPSHOT</logOutputDirectory>
                <backupLogs>true10.0.1-TT.2-SNAPSHOT</backupLogs>
              10.0.1-TT.2-SNAPSHOT</defaults>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <id>execute-plume-installer10.0.1-TT.2-SNAPSHOT</id>
                <phase>prepare-package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>execute10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <properties>
                    <tomee.workdir>${plume.work-dir}10.0.1-TT.2-SNAPSHOT</tomee.workdir>
                    <tomee.webapp>tomee-plume-webapp10.0.1-TT.2-SNAPSHOT</tomee.webapp>
                    <remove.datestamp>${tomee.version}, ${project.version}, ${version.cxf}10.0.1-TT.2-SNAPSHOT</remove.datestamp>
                  10.0.1-TT.2-SNAPSHOT</properties>
                  <source>
                    new commands.SetupCommand(pom: this, log: log, project: project, ant: ant, properties: properties).execute()
                  10.0.1-TT.2-SNAPSHOT</source>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>

          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-assembly-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>plume10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <configuration>
                  <descriptors>
                    <descriptor>src/main/assembly/tomee-plume.xml10.0.1-TT.2-SNAPSHOT</descriptor>
                  10.0.1-TT.2-SNAPSHOT</descriptors>
                  <attach>false10.0.1-TT.2-SNAPSHOT</attach>
                  <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
                  <finalName>apache-tomee-plume-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
                10.0.1-TT.2-SNAPSHOT</configuration>
                <goals>
                  <goal>single10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>

          <plugin>
            <groupId>org.codehaus.mojo10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>build-helper-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>attach-artifacts10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>attach-artifact10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <artifacts>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-plume-${project.version}.zip10.0.1-TT.2-SNAPSHOT</file>
                      <type>zip10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>plume10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                    <artifact>
                      <file>${project.build.directory}/apache-tomee-plume-${project.version}.tar.gz10.0.1-TT.2-SNAPSHOT</file>
                      <type>tar.gz10.0.1-TT.2-SNAPSHOT</type>
                      <classifier>plume10.0.1-TT.2-SNAPSHOT</classifier>
                    10.0.1-TT.2-SNAPSHOT</artifact>
                  10.0.1-TT.2-SNAPSHOT</artifacts>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.tomee.patch10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>tomee-patch-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <configuration>
              <select>apache-tomee-(plus|plume|webprofile|microprofile).*\.zip10.0.1-TT.2-SNAPSHOT</select>
              <skipTransform>true10.0.1-TT.2-SNAPSHOT</skipTransform>
              <createTarGz>true10.0.1-TT.2-SNAPSHOT</createTarGz>
              <skips>
                <jars>
                  <bcpkix-jdk15to18-1.80.jar>org.bouncycastle:bcpkix-jdk15to18:jar:1.8010.0.1-TT.2-SNAPSHOT</bcpkix-jdk15to18-1.80.jar>
                  <bcprov-jdk15to18-1.80.jar>org.bouncycastle:bcprov-jdk15to18:jar:1.8010.0.1-TT.2-SNAPSHOT</bcprov-jdk15to18-1.80.jar>
                  <bcutil-jdk15to18-1.80.jar>org.bouncycastle:bcutil-jdk15to18:jar:1.8010.0.1-TT.2-SNAPSHOT</bcutil-jdk15to18-1.80.jar>
                  <!-- Don't modify bootstrap.jar. Current patch plugin 0.10 has an ambiguity adding classes in more than one target jar if the packages are matching -->
                  <bootstrap.jar>bootstrap.jar10.0.1-TT.2-SNAPSHOT</bootstrap.jar>
                10.0.1-TT.2-SNAPSHOT</jars>
              10.0.1-TT.2-SNAPSHOT</skips>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <goals>
                  <goal>run10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.codehaus.mojo10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>exec-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>3.0.010.0.1-TT.2-SNAPSHOT</version>
            <executions>
              <execution>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>java10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
            <configuration>
              <includeProjectDependencies>true10.0.1-TT.2-SNAPSHOT</includeProjectDependencies>
              <includePluginDependencies>false10.0.1-TT.2-SNAPSHOT</includePluginDependencies>
              <classpathScope>test10.0.1-TT.2-SNAPSHOT</classpathScope>
              <mainClass>org.apache.tomee.bootstrap.GenerateBoms10.0.1-TT.2-SNAPSHOT</mainClass>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>
  10.0.1-TT.2-SNAPSHOT</profiles>
10.0.1-TT.2-SNAPSHOT</project>
