<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <artifactId>microprofile-tck10.0.1-TT.2-SNAPSHOT</artifactId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>
  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <artifactId>microprofile-jwt-tck10.0.1-TT.2-SNAPSHOT</artifactId>
  <name>TomEE :: TCK :: MicroProfile JWT TCK10.0.1-TT.2-SNAPSHOT</name>

  <dependencies>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>mp-jwt10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.johnzon10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>johnzon-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- distro -->
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>zip10.0.1-TT.2-SNAPSHOT</type>
      <classifier>microprofile10.0.1-TT.2-SNAPSHOT</classifier>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- This is the MP-JWT TCK base extension and utility classes -->
    <dependency>
      <groupId>org.eclipse.microprofile.jwt10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>microprofile-jwt-auth-tck10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>jakarta.inject10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakarta.inject10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>      
    10.0.1-TT.2-SNAPSHOT</dependency>

    <!-- This is the actual MP-JWT TCK test classes -->
    <dependency>
      <groupId>org.eclipse.microprofile.jwt10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>microprofile-jwt-auth-tck10.0.1-TT.2-SNAPSHOT</artifactId>
      <type>test-jar10.0.1-TT.2-SNAPSHOT</type>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.testng10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>testng10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-tomee-remote10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.jboss.arquillian.testng10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-testng-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.arquillian}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>io.smallrye.config10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>smallrye-config-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.microprofile.impl.config}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>com.nimbusds10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>nimbus-jose-jwt10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>10.0.110.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.cxf10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>cxf-rt-rs-client10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.cxf}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <!-- needed for the TCK to work correctly -->
        <version>2.1010.0.1-TT.2-SNAPSHOT</version>
        <executions>
          <execution>
            <id>copy-tck-test-suite-file10.0.1-TT.2-SNAPSHOT</id>
            <phase>generate-test-sources10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>unpack10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.eclipse.microprofile.jwt10.0.1-TT.2-SNAPSHOT</groupId>
                  <artifactId>microprofile-jwt-auth-tck10.0.1-TT.2-SNAPSHOT</artifactId>
                  <type>test-jar10.0.1-TT.2-SNAPSHOT</type>
                  <overWrite>true10.0.1-TT.2-SNAPSHOT</overWrite>
                10.0.1-TT.2-SNAPSHOT</artifactItem>
              10.0.1-TT.2-SNAPSHOT</artifactItems>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>3.5.210.0.1-TT.2-SNAPSHOT</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>${project.build.directory}/dependency/suites/tck-base-suite.xml10.0.1-TT.2-SNAPSHOT</suiteXmlFile>
          10.0.1-TT.2-SNAPSHOT</suiteXmlFiles>
          <reuseForks>true10.0.1-TT.2-SNAPSHOT</reuseForks>
          <forkCount>1C10.0.1-TT.2-SNAPSHOT</forkCount>
          <systemPropertyVariables>
            <java.io.tmpdir>./target10.0.1-TT.2-SNAPSHOT</java.io.tmpdir>
          10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-surefire-report-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>generate-test-report10.0.1-TT.2-SNAPSHOT</id>
            <phase>test10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>report-only10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
        <configuration>
          <outputDirectory>${project.build.directory}/surefire-reports10.0.1-TT.2-SNAPSHOT</outputDirectory>
          <outputName>test-report10.0.1-TT.2-SNAPSHOT</outputName>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>

  <profiles>
    <profile>
      <id>mp-tck-all10.0.1-TT.2-SNAPSHOT</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>tomee-plus10.0.1-TT.2-SNAPSHOT</id>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <reuseForks>true10.0.1-TT.2-SNAPSHOT</reuseForks>
                  <forkCount>1C10.0.1-TT.2-SNAPSHOT</forkCount>
                  <systemPropertyVariables>
                    <arquillian.launch>tomee-plus10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <java.io.tmpdir>./target10.0.1-TT.2-SNAPSHOT</java.io.tmpdir>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
              <execution>
                <id>tomee-plume10.0.1-TT.2-SNAPSHOT</id>
                <goals>
                  <goal>test10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <reuseForks>true10.0.1-TT.2-SNAPSHOT</reuseForks>
                  <forkCount>1C10.0.1-TT.2-SNAPSHOT</forkCount>
                  <systemPropertyVariables>
                    <arquillian.launch>tomee-plume10.0.1-TT.2-SNAPSHOT</arquillian.launch>
                    <java.io.tmpdir>./target10.0.1-TT.2-SNAPSHOT</java.io.tmpdir>
                  10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>
  10.0.1-TT.2-SNAPSHOT</profiles>

10.0.1-TT.2-SNAPSHOT</project>
