<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!-- $Rev$ $Date$ -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>

  <parent>
    <artifactId>tomee-project10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>

  <artifactId>tomee10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>pom10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: TomEE10.0.1-TT.2-SNAPSHOT</name>


  <!-- just set the good JPA provider. As openejb-core is needed in all modules it is easier to do it here -->
  <profiles>
    <profile>
      <id>main10.0.1-TT.2-SNAPSHOT</id>
      <activation>
        <activeByDefault>true10.0.1-TT.2-SNAPSHOT</activeByDefault>
      10.0.1-TT.2-SNAPSHOT</activation>
      <modules>
        <module>tomee-config10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-bootstrap10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-loader10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-catalina10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-common10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-myfaces10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-mojarra10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-jdbc10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-jaxrs10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-webapp10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-webaccess10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-plus-webapp10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-plume-webapp10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-webservices10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-embedded10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-microprofile10.0.1-TT.2-SNAPSHOT</module>
        <module>apache-tomee10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-util10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-juli10.0.1-TT.2-SNAPSHOT</module>
        <module>tomee-overlay-runner10.0.1-TT.2-SNAPSHOT</module>
        <!--<module>tomee-deb10.0.1-TT.2-SNAPSHOT</module>-->
        <module>tomee-security10.0.1-TT.2-SNAPSHOT</module>
      10.0.1-TT.2-SNAPSHOT</modules>
    10.0.1-TT.2-SNAPSHOT</profile>
    <profile>
      <id>plume10.0.1-TT.2-SNAPSHOT</id>
      <modules>
        <module>tomee-plume-webapp10.0.1-TT.2-SNAPSHOT</module>
        <module>apache-tomee10.0.1-TT.2-SNAPSHOT</module>
      10.0.1-TT.2-SNAPSHOT</modules>
    10.0.1-TT.2-SNAPSHOT</profile>
    <profile>
      <id>openjpa10.0.1-TT.2-SNAPSHOT</id>
      <activation>
        <activeByDefault>true10.0.1-TT.2-SNAPSHOT</activeByDefault>
      10.0.1-TT.2-SNAPSHOT</activation>
      <dependencies>
        <dependency>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
          <exclusions>
            <exclusion>
              <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
              <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
            10.0.1-TT.2-SNAPSHOT</exclusion>
          10.0.1-TT.2-SNAPSHOT</exclusions>
        10.0.1-TT.2-SNAPSHOT</dependency>
      10.0.1-TT.2-SNAPSHOT</dependencies>
    10.0.1-TT.2-SNAPSHOT</profile>
    <profile>
      <id>hibernate10.0.1-TT.2-SNAPSHOT</id>
      <activation>
        <property>
          <name>hibernate10.0.1-TT.2-SNAPSHOT</name>
        10.0.1-TT.2-SNAPSHOT</property>
      10.0.1-TT.2-SNAPSHOT</activation>
      <dependencies>
        <dependency> <!-- to avoid to force exclusions everywhere -->
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
          <exclusions>
            <exclusion>
              <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
              <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
            10.0.1-TT.2-SNAPSHOT</exclusion>
          10.0.1-TT.2-SNAPSHOT</exclusions>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>openejb-core-hibernate10.0.1-TT.2-SNAPSHOT</artifactId>
          <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
          <type>pom10.0.1-TT.2-SNAPSHOT</type>
          <exclusions>
            <exclusion>
              <groupId>*10.0.1-TT.2-SNAPSHOT</groupId>
              <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
            10.0.1-TT.2-SNAPSHOT</exclusion>
          10.0.1-TT.2-SNAPSHOT</exclusions>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
          <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
          <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
      10.0.1-TT.2-SNAPSHOT</dependencies>
    10.0.1-TT.2-SNAPSHOT</profile>
  10.0.1-TT.2-SNAPSHOT</profiles>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>maven-pmd-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</plugin>
      10.0.1-TT.2-SNAPSHOT</plugins>
    10.0.1-TT.2-SNAPSHOT</pluginManagement>
  10.0.1-TT.2-SNAPSHOT</build>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.eclipse.jdt10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>ecj10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${version.ecj}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>jakarta.servlet10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>jstl10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>1.210.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.velocity10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>velocity-engine-core10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>2.4.110.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.geronimo.specs10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>geronimo-j2ee-deployment_1.1_spec10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>1.110.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.ant10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>ant-nodeps10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>1.8.110.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-jdbc10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-dbcp10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-catalina-ha10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-coyote10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-jasper10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
        <exclusions>
          <exclusion>
            <groupId>org.eclipse.jdt10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>ecj10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
        10.0.1-TT.2-SNAPSHOT</exclusions>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openwebbeans-jsf10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${version.openwebbeans}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>myfaces-api10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${version.myfaces}10.0.1-TT.2-SNAPSHOT</version>
        <exclusions>
          <exclusion>
            <groupId>org.apache.geronimo.specs10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>jakarta.enterprise10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.enterprise.cdi-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>jakarta.inject10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.inject-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
        10.0.1-TT.2-SNAPSHOT</exclusions>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>myfaces-impl10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${version.myfaces}10.0.1-TT.2-SNAPSHOT</version>
        <exclusions>
          <exclusion>
            <groupId>org.apache.geronimo.specs10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>jakarta.validation10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.validation-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>jakarta.annotation10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.annotation-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>jakarta.enterprise10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.enterprise.cdi-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
          <exclusion>
            <groupId>jakarta.inject10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.inject-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
        10.0.1-TT.2-SNAPSHOT</exclusions>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-client10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
        <type>zip10.0.1-TT.2-SNAPSHOT</type>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-server10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-ejbd10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-rest10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-cxf-rs10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-http10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomcat-websocket10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-cxf-transport10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-loader10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-jee10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>org.glassfish10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>jakarta.faces10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${version.mojarra}10.0.1-TT.2-SNAPSHOT</version>
        <exclusions>
          <exclusion>
            <groupId>jakarta.annotation10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.annotation-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
        10.0.1-TT.2-SNAPSHOT</exclusions>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-webservices10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-cxf10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
        <exclusions>
          <exclusion>
            <groupId>jakarta.xml.soap10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.xml.soap-api10.0.1-TT.2-SNAPSHOT</artifactId>
          10.0.1-TT.2-SNAPSHOT</exclusion>
        10.0.1-TT.2-SNAPSHOT</exclusions>
      10.0.1-TT.2-SNAPSHOT</dependency>
      <dependency>
        <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>openejb-core-eclipselink10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      10.0.1-TT.2-SNAPSHOT</dependency>
    10.0.1-TT.2-SNAPSHOT</dependencies>
  10.0.1-TT.2-SNAPSHOT</dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
10.0.1-TT.2-SNAPSHOT</project>
