<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~   http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>

  <parent>
    <groupId>org.superbiz10.0.1-TT.2-SNAPSHOT</groupId>
    <artifactId>resources-jmx10.0.1-TT.2-SNAPSHOT</artifactId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>

  <artifactId>resources-jmx-ejb10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>ejb10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: Examples :: Resources/JMX Example :: EJB Module10.0.1-TT.2-SNAPSHOT</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-ejb-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>2.310.0.1-TT.2-SNAPSHOT</version>
        <configuration>
          <ejbVersion>3.110.0.1-TT.2-SNAPSHOT</ejbVersion>
          <archive>
            <manifest>
              <addDefaultImplementationEntries>true10.0.1-TT.2-SNAPSHOT</addDefaultImplementationEntries>
              <addDefaultSpecificationEntries>true10.0.1-TT.2-SNAPSHOT</addDefaultSpecificationEntries>
            10.0.1-TT.2-SNAPSHOT</manifest>
          10.0.1-TT.2-SNAPSHOT</archive>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>
  <dependencies>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-tomee-remote10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-provisionning10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.arquillian.junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-junit-container10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.9.3.Final10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-lang310.0.1-TT.2-SNAPSHOT</artifactId>
      <version>3.17.010.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>ziplock10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap.resolver10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-resolver-impl-maven10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>3.3.310.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <artifactId>aether-api10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.eclipse.aether10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>aether-impl10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.eclipse.aether10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>aether-spi10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.eclipse.aether10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>aether-util10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.eclipse.aether10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>aether-connector-basic10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.eclipse.aether10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>aether-transport-wagon10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.eclipse.aether10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.maven10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>maven-aether-provider10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>3.3.910.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
10.0.1-TT.2-SNAPSHOT</project>
