<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>tck10.0.1-TT.2-SNAPSHOT</artifactId>
        <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
        <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</parent>

    <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
    <artifactId>concurrency-signature-test10.0.1-TT.2-SNAPSHOT</artifactId>
    <name>TomEE :: TCK :: Concurrency Signature Tests10.0.1-TT.2-SNAPSHOT</name>

    <properties>
        <jakarta.concurrent.version>3.0.410.0.1-TT.2-SNAPSHOT</jakarta.concurrent.version>
        <sigtest.version>2.310.0.1-TT.2-SNAPSHOT</sigtest.version>
    10.0.1-TT.2-SNAPSHOT</properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.enterprise.concurrent10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta.enterprise.concurrent-tck10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${jakarta.concurrent.version}10.0.1-TT.2-SNAPSHOT</version>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
            <groupId>jakarta.tck10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>sigtest-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${sigtest.version}10.0.1-TT.2-SNAPSHOT</version>
            <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
            <groupId>org.testng10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>testng10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
            <groupId>org.slf4j10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>slf4j-api10.0.1-TT.2-SNAPSHOT</artifactId>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
            <groupId>org.slf4j10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>slf4j-jdk1410.0.1-TT.2-SNAPSHOT</artifactId>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <!-- Arquillian Implementation for TestNG -->
        <dependency>
            <groupId>org.jboss.arquillian.testng10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>arquillian-testng-container10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${version.arquillian}10.0.1-TT.2-SNAPSHOT</version>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <!-- Arquillian Deps for Apache TomEE -->
        <dependency>
            <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
            <type>zip10.0.1-TT.2-SNAPSHOT</type>
            <classifier>plus10.0.1-TT.2-SNAPSHOT</classifier>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
            <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>arquillian-tomee-remote10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
            <scope>test10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
    10.0.1-TT.2-SNAPSHOT</dependencies>

    <profiles>
        <profile>
            <id>tck-concurrency10.0.1-TT.2-SNAPSHOT</id>
            <build>
                <testResources>
                    <testResource>
                        <directory>src/test/resources10.0.1-TT.2-SNAPSHOT</directory>
                        <filtering>true10.0.1-TT.2-SNAPSHOT</filtering>
                    10.0.1-TT.2-SNAPSHOT</testResource>
                10.0.1-TT.2-SNAPSHOT</testResources>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <executions>
                            <execution>
                                <id>copy10.0.1-TT.2-SNAPSHOT</id>
                                <phase>generate-test-resources10.0.1-TT.2-SNAPSHOT</phase>
                                <goals>
                                    <goal>copy10.0.1-TT.2-SNAPSHOT</goal>
                                10.0.1-TT.2-SNAPSHOT</goals>
                                <configuration>
                                    <artifactItems>
                                        <artifactItem>
                                            <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
                                            <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
                                            <version>${version.jakartaee-api}10.0.1-TT.2-SNAPSHOT</version>
                                            <type>jar10.0.1-TT.2-SNAPSHOT</type>
                                            <overWrite>true10.0.1-TT.2-SNAPSHOT</overWrite>
                                            <outputDirectory>${project.build.directory}/signaturedirectory
                                            10.0.1-TT.2-SNAPSHOT</outputDirectory>
                                            <destFileName>jakartaee-api.jar10.0.1-TT.2-SNAPSHOT</destFileName>
                                        10.0.1-TT.2-SNAPSHOT</artifactItem>
                                    10.0.1-TT.2-SNAPSHOT</artifactItems>
                                10.0.1-TT.2-SNAPSHOT</configuration>
                            10.0.1-TT.2-SNAPSHOT</execution>
                        10.0.1-TT.2-SNAPSHOT</executions>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <version>${surefire.version}10.0.1-TT.2-SNAPSHOT</version>
                        <configuration>
                            <reuseForks>false10.0.1-TT.2-SNAPSHOT</reuseForks>
                            <forkCount>110.0.1-TT.2-SNAPSHOT</forkCount>
                            <dependenciesToScan>
                                <dependency>jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-tck10.0.1-TT.2-SNAPSHOT</dependency>
                            10.0.1-TT.2-SNAPSHOT</dependenciesToScan>
                            <includes>
                                <include>**/signature/**10.0.1-TT.2-SNAPSHOT</include>
                            10.0.1-TT.2-SNAPSHOT</includes>
                            <systemProperties>
                                <java.util.logging.config.file>logging.properties10.0.1-TT.2-SNAPSHOT</java.util.logging.config.file>
                                <jimage.dir>${project.build.directory}/jimage10.0.1-TT.2-SNAPSHOT</jimage.dir>
                                <signature.sigTestClasspath>
                                    ${project.build.directory}/signaturedirectory/jakartaee-api.jar:${project.build.directory}/jimage/java.base:${project.build.directory}/jimage/java.rmi:${project.build.directory}/jimage/java.sql:${project.build.directory}/jimage/java.naming
                                10.0.1-TT.2-SNAPSHOT</signature.sigTestClasspath>
                            10.0.1-TT.2-SNAPSHOT</systemProperties>
                        10.0.1-TT.2-SNAPSHOT</configuration>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-surefire-report-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <version>${surefire.version}10.0.1-TT.2-SNAPSHOT</version>
                        <executions>
                            <execution>
                                <id>generate-test-report10.0.1-TT.2-SNAPSHOT</id>
                                <phase>test10.0.1-TT.2-SNAPSHOT</phase>
                                <goals>
                                    <goal>report-only10.0.1-TT.2-SNAPSHOT</goal>
                                10.0.1-TT.2-SNAPSHOT</goals>
                            10.0.1-TT.2-SNAPSHOT</execution>
                        10.0.1-TT.2-SNAPSHOT</executions>
                        <configuration>
                            <outputDirectory>${project.build.directory}/surefire-reports10.0.1-TT.2-SNAPSHOT</outputDirectory>
                            <outputName>test-report10.0.1-TT.2-SNAPSHOT</outputName>
                        10.0.1-TT.2-SNAPSHOT</configuration>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                10.0.1-TT.2-SNAPSHOT</plugins>
            10.0.1-TT.2-SNAPSHOT</build>
        10.0.1-TT.2-SNAPSHOT</profile>
    10.0.1-TT.2-SNAPSHOT</profiles>
10.0.1-TT.2-SNAPSHOT</project>