<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!-- $Rev$ $Date$ -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>

  <parent>
    <artifactId>assembly10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>

  <artifactId>openejb-standalone10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>pom10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: Assembly :: Standalone10.0.1-TT.2-SNAPSHOT</name>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources10.0.1-TT.2-SNAPSHOT</directory>
        <filtering>true10.0.1-TT.2-SNAPSHOT</filtering>
      10.0.1-TT.2-SNAPSHOT</resource>
    10.0.1-TT.2-SNAPSHOT</resources>
    <plugins>
      <!--
      Create an empty directory which will be copied
      twice by the assembly plugin to create the
      conf/ and logs/ directories
      -->
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-antrun-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>cleanup-target10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <configuration>
              <target>
                <delete dir="${basedir}/target/classes" />
                <delete dir="${basedir}/target/archive-tmp" />
              10.0.1-TT.2-SNAPSHOT</target>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <goals>
              <goal>run10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-resources-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <configuration>
          <nonFilteredFileExtensions>
            <nonFilteredFileExtension>exe10.0.1-TT.2-SNAPSHOT</nonFilteredFileExtension>
          10.0.1-TT.2-SNAPSHOT</nonFilteredFileExtensions>
        10.0.1-TT.2-SNAPSHOT</configuration>
        <executions>
          <execution>
            <id>filter-resources10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>resources10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-assembly-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>assembly-bin-distributions10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>attached10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
        <configuration>
          <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
          <descriptors>
            <descriptor>src/main/assembly/dos.xml10.0.1-TT.2-SNAPSHOT</descriptor>
            <descriptor>src/main/assembly/unix.xml10.0.1-TT.2-SNAPSHOT</descriptor>
          10.0.1-TT.2-SNAPSHOT</descriptors>
          <archive>
            <manifest>
              <mainClass>org.apache.openejb.test.Main10.0.1-TT.2-SNAPSHOT</mainClass>
            10.0.1-TT.2-SNAPSHOT</manifest>
          10.0.1-TT.2-SNAPSHOT</archive>
          <finalName>apache-openejb-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>
  <dependencies>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-loader10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.geronimo.mail10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>geronimo-mail_2.1_provider10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-client10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-server10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-ejbd10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-multicast10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-hsql10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <optional>true10.0.1-TT.2-SNAPSHOT</optional>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-http10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <optional>true10.0.1-TT.2-SNAPSHOT</optional>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf-rs10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <optional>true10.0.1-TT.2-SNAPSHOT</optional>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-daemon10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <optional>true10.0.1-TT.2-SNAPSHOT</optional>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-itests-client10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-itests-beans10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
  <profiles>
    <profile>
      <id>itest10.0.1-TT.2-SNAPSHOT</id>
      <properties>
        <openejb.debug.suspend>n10.0.1-TT.2-SNAPSHOT</openejb.debug.suspend>
        <openejb.debug.port>500510.0.1-TT.2-SNAPSHOT</openejb.debug.port>
      10.0.1-TT.2-SNAPSHOT</properties>
      <dependencies>
        <dependency>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>openejb-itests-client10.0.1-TT.2-SNAPSHOT</artifactId>
          <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>openejb-itests-beans10.0.1-TT.2-SNAPSHOT</artifactId>
          <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
          <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
          <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
      10.0.1-TT.2-SNAPSHOT</dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-antrun-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <executions>
              <execution>
                <id>setup:openejb:unjar10.0.1-TT.2-SNAPSHOT</id>
                <phase>integration-test10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>run10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
                <configuration>
                  <target>
                    <property name="targetDir" value="${basedir}/target/" />
                    <property name="openejb.home" value="${targetDir}/openejb-${project.version}" />
                    <property name="openejb.dist" value="${targetDir}/openejb-${project.version}-bin.zip" />
                    <property name="tomee.version" value="${project.version}" />

                    <unjar src="${openejb.dist}" dest="${targetDir}" />
                    <copy file="${targetDir}/openejb-${project.version}-test.jar" todir="${openejb.home}/apps" />

                    <java classname="org.apache.openejb.test.Main" fork="yes">
                      <classpath>
                        <pathelement location="${targetDir}/openejb-${project.version}-test.jar" />
                        <fileset dir="${openejb.home}/lib">
                          <include name="*.jar" />
                        10.0.1-TT.2-SNAPSHOT</fileset>
                      10.0.1-TT.2-SNAPSHOT</classpath>
                      <sysproperty key="openejb.home" value="${openejb.home}" />
                      <jvmarg value="-agentlib:jdwp=transport=dt_socket,server=y,suspend=${openejb.debug.suspend},address=${openejb.debug.port}" />
                      <arg value="local" />
                    10.0.1-TT.2-SNAPSHOT</java>

                    <java jar="target/openejb-{project.version}-test.jar" fork="yes">
                      <sysproperty key="openejb.home" value="${openejb.home}" />
                      <jvmarg value="-agentlib:jdwp=transport=dt_socket,server=y,suspend=${openejb.debug.suspend},address=${openejb.debug.port}" />
                      <arg value="remote" />
                    10.0.1-TT.2-SNAPSHOT</java>

                    <java jar="target/openejb-{project.version}-test.jar" fork="yes">
                      <sysproperty key="openejb.home" value="${openejb.home}" />
                      <jvmarg value="-agentlib:jdwp=transport=dt_socket,server=y,suspend=${openejb.debug.suspend},address=${openejb.debug.port}" />
                      <arg value="http" />
                    10.0.1-TT.2-SNAPSHOT</java>

                  10.0.1-TT.2-SNAPSHOT</target>
                10.0.1-TT.2-SNAPSHOT</configuration>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>
  10.0.1-TT.2-SNAPSHOT</profiles>
10.0.1-TT.2-SNAPSHOT</project>
