<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <groupId>org.superbiz10.0.1-TT.2-SNAPSHOT</groupId>
  <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  <artifactId>mp-metrics-metered10.0.1-TT.2-SNAPSHOT</artifactId>
  <name>TomEE :: Examples :: MicroProfile Metrics Metered10.0.1-TT.2-SNAPSHOT</name>
  <packaging>war10.0.1-TT.2-SNAPSHOT</packaging>
  <properties>
    <version.jakartaee-api>10.010.0.1-TT.2-SNAPSHOT</version.jakartaee-api>
    <version.microprofile.metrics>5.0.210.0.1-TT.2-SNAPSHOT</version.microprofile.metrics>
    <version.arquillian.bom>1.7.1.Final10.0.1-TT.2-SNAPSHOT</version.arquillian.bom>
    <junit.version>4.13.210.0.1-TT.2-SNAPSHOT</junit.version>
    <tomee.version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</tomee.version>
  10.0.1-TT.2-SNAPSHOT</properties>
  <dependencies>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.jakartaee-api}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.eclipse.microprofile.metrics10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>microprofile-metrics-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.microprofile.metrics}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf-rs10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.arquillian.junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-junit-container10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.9.3.Final10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>arquillian-tomee-remote10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>apache-tomee10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
      <type>zip10.0.1-TT.2-SNAPSHOT</type>
      <classifier>microprofile10.0.1-TT.2-SNAPSHOT</classifier>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-compiler-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>3.13.010.0.1-TT.2-SNAPSHOT</version>
        <configuration>
          <source>1710.0.1-TT.2-SNAPSHOT</source>
          <target>1710.0.1-TT.2-SNAPSHOT</target>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-war-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>3.4.010.0.1-TT.2-SNAPSHOT</version>
        <configuration>
          <failOnMissingWebXml>false10.0.1-TT.2-SNAPSHOT</failOnMissingWebXml>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.tomee.maven10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>tomee-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>${tomee.version}10.0.1-TT.2-SNAPSHOT</version>
        <configuration>
          <tomeeClassifier>microprofile10.0.1-TT.2-SNAPSHOT</tomeeClassifier>
          <context>${project.artifactId}10.0.1-TT.2-SNAPSHOT</context>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>

    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>
  <!-- This section allows you to configure where to publish libraries for
  sharing. It is not required and may be deleted. For more information see:
  http://maven.apache.org/plugins/maven-deploy-plugin/ -->
  <distributionManagement>
    <repository>
      <id>localhost10.0.1-TT.2-SNAPSHOT</id>
      <url>file://${basedir}/target/repo/10.0.1-TT.2-SNAPSHOT</url>
    10.0.1-TT.2-SNAPSHOT</repository>
    <snapshotRepository>
      <id>localhost10.0.1-TT.2-SNAPSHOT</id>
      <url>file://${basedir}/target/snapshot-repo/10.0.1-TT.2-SNAPSHOT</url>
    10.0.1-TT.2-SNAPSHOT</snapshotRepository>
  10.0.1-TT.2-SNAPSHOT</distributionManagement>
10.0.1-TT.2-SNAPSHOT</project>
