<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!--test 2-->
<!-- $Rev$ $Date$ -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <parent>
    <artifactId>tomee-project10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>
  <artifactId>examples10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>pom10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: Examples10.0.1-TT.2-SNAPSHOT</name>
  <modules>
    <module>access-timeout-meta10.0.1-TT.2-SNAPSHOT</module>
    <module>access-timeout10.0.1-TT.2-SNAPSHOT</module>
    <module>alternate-descriptors10.0.1-TT.2-SNAPSHOT</module>
    <module>application-composer10.0.1-TT.2-SNAPSHOT</module>
    <module>applicationcomposer-jaxws-cdi10.0.1-TT.2-SNAPSHOT</module>
    <module>applicationexception10.0.1-TT.2-SNAPSHOT</module>
    <module>arquillian-jpa10.0.1-TT.2-SNAPSHOT</module>
    <module>async-methods10.0.1-TT.2-SNAPSHOT</module>
    <module>async-postconstruct10.0.1-TT.2-SNAPSHOT</module>
    <module>bean-validation-design-by-contract10.0.1-TT.2-SNAPSHOT</module>
    <module>bval-evaluation-redeployment10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-alternative-and-stereotypes10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-application-scope10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-basic10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-dynamic-inject10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-ejbcontext-jaas10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-events10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-interceptors10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-produces-disposes10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-produces-field10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-qualifier10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-realm10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-request-scope10.0.1-TT.2-SNAPSHOT</module>
    <module>cdi-session-scope10.0.1-TT.2-SNAPSHOT</module>
    <module>change-jaxws-url10.0.1-TT.2-SNAPSHOT</module>
    <module>component-interfaces10.0.1-TT.2-SNAPSHOT</module>
    <module>client-resource-lookup-preview10.0.1-TT.2-SNAPSHOT</module>
    <module>connector-ear10.0.1-TT.2-SNAPSHOT</module>
    <module>connector-war10.0.1-TT.2-SNAPSHOT</module>
    <module>cucumber-jvm10.0.1-TT.2-SNAPSHOT</module>
    <module>custom-injection10.0.1-TT.2-SNAPSHOT</module>
    <module>datasource-ciphered-password10.0.1-TT.2-SNAPSHOT</module>
    <module>datasource-definition10.0.1-TT.2-SNAPSHOT</module>
    <module>datasource-versioning10.0.1-TT.2-SNAPSHOT</module>
    <module>decorators10.0.1-TT.2-SNAPSHOT</module>
    <module>dynamic-dao-implementation10.0.1-TT.2-SNAPSHOT</module>
    <module>dynamic-datasource-routing10.0.1-TT.2-SNAPSHOT</module>
    <module>dynamic-implementation10.0.1-TT.2-SNAPSHOT</module>
    <module>dynamic-proxy-to-access-mbean10.0.1-TT.2-SNAPSHOT</module>
    <module>ear-testing10.0.1-TT.2-SNAPSHOT</module>
    <module>ejb-examples10.0.1-TT.2-SNAPSHOT</module>
    <module>ejb-remote-call10.0.1-TT.2-SNAPSHOT</module>
    <module>ejb-remote-call-210.0.1-TT.2-SNAPSHOT</module>
    <module>ejb-webservice10.0.1-TT.2-SNAPSHOT</module>
    <module>groovy-cdi10.0.1-TT.2-SNAPSHOT</module>
    <module>groovy-jpa10.0.1-TT.2-SNAPSHOT</module>
    <module>helloworld-weblogic10.0.1-TT.2-SNAPSHOT</module>
    <module>injection-of-connectionfactory10.0.1-TT.2-SNAPSHOT</module>
    <module>injection-of-datasource10.0.1-TT.2-SNAPSHOT</module>
    <module>injection-of-ejbs10.0.1-TT.2-SNAPSHOT</module>
    <module>injection-of-entitymanager10.0.1-TT.2-SNAPSHOT</module>
    <module>injection-of-env-entry10.0.1-TT.2-SNAPSHOT</module>
    <module>interceptors10.0.1-TT.2-SNAPSHOT</module>
    <module>javamail10.0.1-TT.2-SNAPSHOT</module>
    <module>javamail-velocity10.0.1-TT.2-SNAPSHOT</module>
    <module>java-modules10.0.1-TT.2-SNAPSHOT</module>
    <module>jaxrs-filter10.0.1-TT.2-SNAPSHOT</module>
    <module>jaxrs-json-provider-jettison10.0.1-TT.2-SNAPSHOT</module>
    <module>jpa-eclipselink10.0.1-TT.2-SNAPSHOT</module>
    <module>jpa-hibernate10.0.1-TT.2-SNAPSHOT</module>
    <module>jpa-hibernate-arquillian10.0.1-TT.2-SNAPSHOT</module>
    <module>jpa-enumerated10.0.1-TT.2-SNAPSHOT</module>
    <module>jsf-cdi-and-ejb10.0.1-TT.2-SNAPSHOT</module>
    <module>junit5-application-composer10.0.1-TT.2-SNAPSHOT</module>
    <module>junit5-arquillian-multiple-tomee10.0.1-TT.2-SNAPSHOT</module>
    <module>junit5-arquillian-simple-websockets10.0.1-TT.2-SNAPSHOT</module>
    <module>lookup-of-ejbs10.0.1-TT.2-SNAPSHOT</module>
    <module>lookup-of-ejbs-with-descriptor10.0.1-TT.2-SNAPSHOT</module>
    <!-- Does not work with Java 9+ because of the modules. Needs more work
    <module>mbean-auto-registration10.0.1-TT.2-SNAPSHOT</module>
    -->
    <module>movies-complete-meta10.0.1-TT.2-SNAPSHOT</module>
    <module>movies-complete10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-config-example10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-config-source-database10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-faulttolerance-fallback10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-faulttolerance-retry10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-faulttolerance-timeout10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-jwt-bean-validation10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-jwt-bean-validation-strongly-typed10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-metrics-counted10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-metrics-histogram10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-metrics-timed10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-metrics-gauge10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-metrics-metered10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-rest-jwt-jwk10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-rest-jwt-principal10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-rest-jwt-public-key10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-rest-client10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-custom-healthcheck10.0.1-TT.2-SNAPSHOT</module>
    <module>mp-openapi-reader10.0.1-TT.2-SNAPSHOT</module>
    <module>mtom10.0.1-TT.2-SNAPSHOT</module>
    <module>multi-jpa-provider-testing10.0.1-TT.2-SNAPSHOT</module>
    <module>multiple-arquillian-adapters10.0.1-TT.2-SNAPSHOT</module>
    <module>multiple-tomee-arquillian10.0.1-TT.2-SNAPSHOT</module>
    <module>persistence-fragment10.0.1-TT.2-SNAPSHOT</module>
    <module>pojo-webservice10.0.1-TT.2-SNAPSHOT</module>
<!--    <module>polling-parent10.0.1-TT.2-SNAPSHOT</module>-->
    <module>quartz-app10.0.1-TT.2-SNAPSHOT</module>
    <module>realm-in-tomee10.0.1-TT.2-SNAPSHOT</module>
    <module>reload-persistence-unit-properties10.0.1-TT.2-SNAPSHOT</module>
    <module>resources-declared-in-webapp10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-applicationcomposer-mockito10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-applicationcomposer10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-cdi10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-jaas10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-on-ejb10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-example10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-example-with-application10.0.1-TT.2-SNAPSHOT</module>
    <module>rest-xml-json10.0.1-TT.2-SNAPSHOT</module>
    <module>scala-basic10.0.1-TT.2-SNAPSHOT</module>
    <module>schedule-expression10.0.1-TT.2-SNAPSHOT</module>
    <module>schedule-events10.0.1-TT.2-SNAPSHOT</module>
    <module>schedule-methods-meta10.0.1-TT.2-SNAPSHOT</module>
    <module>schedule-methods10.0.1-TT.2-SNAPSHOT</module>
    <module>server-events10.0.1-TT.2-SNAPSHOT</module>
    <module>serverless-builder10.0.1-TT.2-SNAPSHOT</module>
    <module>serverless-tomee-webprofile10.0.1-TT.2-SNAPSHOT</module>
    <module>serverless-tomee-microprofile10.0.1-TT.2-SNAPSHOT</module>
    <module>serverless-tomee-plume10.0.1-TT.2-SNAPSHOT</module>
    <module>serverless-tomee-plus10.0.1-TT.2-SNAPSHOT</module>
    <module>singleton-startup-ordering10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-cdi-interceptor10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-ear10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-cmp210.0.1-TT.2-SNAPSHOT</module>
    <module>simple-jms10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-jms-context10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-mdb-and-cdi10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-mdb10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-mdb-with-descriptor10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-remote-tomcatusers10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-rest10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-singleton10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-stateful10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-stateful-callbacks10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-stateless10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-stateless-callbacks10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-stateless-with-descriptor10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-webservice10.0.1-TT.2-SNAPSHOT</module>
    <module>simple-webservice-without-interface10.0.1-TT.2-SNAPSHOT</module>
    <module>async-servlet10.0.1-TT.2-SNAPSHOT</module>
    <module>struts10.0.1-TT.2-SNAPSHOT</module>
    <module>telephone-stateful10.0.1-TT.2-SNAPSHOT</module>
    <module>testcase-injection10.0.1-TT.2-SNAPSHOT</module>
    <module>testing-security-meta10.0.1-TT.2-SNAPSHOT</module>
    <module>testing-security10.0.1-TT.2-SNAPSHOT</module>
    <module>testing-security-210.0.1-TT.2-SNAPSHOT</module>
    <module>testing-security-310.0.1-TT.2-SNAPSHOT</module>
    <module>testing-security-410.0.1-TT.2-SNAPSHOT</module>
    <module>testing-transactions10.0.1-TT.2-SNAPSHOT</module>
    <module>testing-transactions-bmt10.0.1-TT.2-SNAPSHOT</module>
<!--    <module>tomee-jersey-eclipselink10.0.1-TT.2-SNAPSHOT</module>-->
    <module>tomee-jms-portability10.0.1-TT.2-SNAPSHOT</module>
    <module>transaction-rollback10.0.1-TT.2-SNAPSHOT</module>
    <module>troubleshooting10.0.1-TT.2-SNAPSHOT</module>
    <module>webservice-attachments10.0.1-TT.2-SNAPSHOT</module>
    <module>webservice-inheritance10.0.1-TT.2-SNAPSHOT</module>
    <module>webservice-security10.0.1-TT.2-SNAPSHOT</module>
    <module>webservice-ssl-client-cert10.0.1-TT.2-SNAPSHOT</module>
<!--    <module>webservice-ws-security10.0.1-TT.2-SNAPSHOT</module>-->
<!--    <module>webservice-ws-with-resources-config10.0.1-TT.2-SNAPSHOT</module>-->
    <module>webservice-handlerchain10.0.1-TT.2-SNAPSHOT</module>
    <module>webservice-holder10.0.1-TT.2-SNAPSHOT</module>
    <module>moviefun10.0.1-TT.2-SNAPSHOT</module>
    <module>moviefun-rest10.0.1-TT.2-SNAPSHOT</module>
    <module>resources-jmx-example10.0.1-TT.2-SNAPSHOT</module>
    <module>websocket-tls-basic-auth10.0.1-TT.2-SNAPSHOT</module>
    <module>concurrency-utils10.0.1-TT.2-SNAPSHOT</module>
    <module>jsonb-configuration10.0.1-TT.2-SNAPSHOT</module>
    <module>jsonb-custom-serializer10.0.1-TT.2-SNAPSHOT</module>
    <module>cloud-tomee-azure10.0.1-TT.2-SNAPSHOT</module>
    <module>xa-datasource10.0.1-TT.2-SNAPSHOT</module>
    <module>websocket-jms10.0.1-TT.2-SNAPSHOT</module>
    <module>activemq-multiple-brokers10.0.1-TT.2-SNAPSHOT</module>

    <!-- Jakarta Security Examples -->
    <module>security-tomcat-user-identitystore10.0.1-TT.2-SNAPSHOT</module>
    <module>security-custom-identitystore10.0.1-TT.2-SNAPSHOT</module>
    <module>security-openid10.0.1-TT.2-SNAPSHOT</module>

  10.0.1-TT.2-SNAPSHOT</modules>
  <profiles>
    <profile>
      <id>apache-release10.0.1-TT.2-SNAPSHOT</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-javadoc-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>3.11.210.0.1-TT.2-SNAPSHOT</version>
            <configuration>
              <skip>true10.0.1-TT.2-SNAPSHOT</skip>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</plugin>
          <plugin>
            <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>maven-assembly-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
            <inherited>false10.0.1-TT.2-SNAPSHOT</inherited>
            <configuration>
              <descriptors>
                <descriptor>src.xml10.0.1-TT.2-SNAPSHOT</descriptor>
              10.0.1-TT.2-SNAPSHOT</descriptors>
              <tarLongFileMode>gnu10.0.1-TT.2-SNAPSHOT</tarLongFileMode>
              <finalName>openejb-examples-${project.version}10.0.1-TT.2-SNAPSHOT</finalName>
            10.0.1-TT.2-SNAPSHOT</configuration>
            <executions>
              <execution>
                <id>make-assembly10.0.1-TT.2-SNAPSHOT</id>
                <phase>package10.0.1-TT.2-SNAPSHOT</phase>
                <goals>
                  <goal>single10.0.1-TT.2-SNAPSHOT</goal>
                10.0.1-TT.2-SNAPSHOT</goals>
              10.0.1-TT.2-SNAPSHOT</execution>
            10.0.1-TT.2-SNAPSHOT</executions>
          10.0.1-TT.2-SNAPSHOT</plugin>
        10.0.1-TT.2-SNAPSHOT</plugins>
      10.0.1-TT.2-SNAPSHOT</build>
    10.0.1-TT.2-SNAPSHOT</profile>
  10.0.1-TT.2-SNAPSHOT</profiles>
10.0.1-TT.2-SNAPSHOT</project>
