<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>org.superbiz.quartz10.0.1-TT.2-SNAPSHOT</groupId>
    <artifactId>quartz-app10.0.1-TT.2-SNAPSHOT</artifactId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>
  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <artifactId>quartz-ra10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>jar10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: Examples :: Quartz :: Quartz Resource Adapter10.0.1-TT.2-SNAPSHOT</name>
  <description>
    Maven doesn't allow rar files in the test classpath for some reason,
    so we have to pull this trick to get it in the classpath.
  10.0.1-TT.2-SNAPSHOT</description>
  <dependencies>
    <dependency>
      <groupId>org.quartz-scheduler10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>quartz10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee.bom10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-plus10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
  <!--
  This section allows you to configure where to publish libraries for sharing.
  It is not required and may be deleted.  For more information see:
  http://maven.apache.org/plugins/maven-deploy-plugin/
  -->
  <distributionManagement>
    <repository>
      <id>localhost10.0.1-TT.2-SNAPSHOT</id>
      <url>file://${basedir}/target/repo/10.0.1-TT.2-SNAPSHOT</url>
    10.0.1-TT.2-SNAPSHOT</repository>
    <snapshotRepository>
      <id>localhost10.0.1-TT.2-SNAPSHOT</id>
      <url>file://${basedir}/target/snapshot-repo/10.0.1-TT.2-SNAPSHOT</url>
    10.0.1-TT.2-SNAPSHOT</snapshotRepository>
  10.0.1-TT.2-SNAPSHOT</distributionManagement>
10.0.1-TT.2-SNAPSHOT</project>
