<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
    <parent>
        <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>jax-rs10.0.1-TT.2-SNAPSHOT</artifactId>
        <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</parent>

    <artifactId>jax-rs-signature-test10.0.1-TT.2-SNAPSHOT</artifactId>
    <name>TomEE :: TCK :: JAX-RS TCK :: Signature Test10.0.1-TT.2-SNAPSHOT</name>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${version.jakartaee-api}10.0.1-TT.2-SNAPSHOT</version>
            <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
        10.0.1-TT.2-SNAPSHOT</dependency>
        <dependency>
            <groupId>jakarta.ws.rs10.0.1-TT.2-SNAPSHOT</groupId>
            <artifactId>jakarta-restful-ws-tck10.0.1-TT.2-SNAPSHOT</artifactId>
            <version>${jaxrs.tck.version}10.0.1-TT.2-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.ws.rs10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>jakarta.ws.rs-api10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
                <exclusion>
                    <groupId>jakarta.json.bind10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>jakarta.json.bind-api10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
                <exclusion>
                    <groupId>jakarta.json10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>jakarta.json-api10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
                <exclusion>
                    <groupId>jakarta.xml.bind10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>jakarta.xml.bind-api10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
                <exclusion>
                    <groupId>jakarta.annotation10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>jakarta.annotation-api10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
                <exclusion>
                    <groupId>jakarta.activation10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>jakarta.activation-api10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
                <exclusion>
                    <groupId>org.netbeans.tools10.0.1-TT.2-SNAPSHOT</groupId>
                    <artifactId>sigtest-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                10.0.1-TT.2-SNAPSHOT</exclusion>
            10.0.1-TT.2-SNAPSHOT</exclusions>
        10.0.1-TT.2-SNAPSHOT</dependency>
    10.0.1-TT.2-SNAPSHOT</dependencies>

    <profiles>
        <profile>
            <id>tck-jax-rs10.0.1-TT.2-SNAPSHOT</id>
            <build>
                <testResources>
                    <testResource>
                        <directory>src/test/resources10.0.1-TT.2-SNAPSHOT</directory>
                        <filtering>true10.0.1-TT.2-SNAPSHOT</filtering>
                    10.0.1-TT.2-SNAPSHOT</testResource>
                10.0.1-TT.2-SNAPSHOT</testResources>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-antrun-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <configuration>
                            <skip>true10.0.1-TT.2-SNAPSHOT</skip>
                        10.0.1-TT.2-SNAPSHOT</configuration>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <version>3.8.010.0.1-TT.2-SNAPSHOT</version>
                        <executions>
                            <execution>
                                <id>copy-tck-cdi-api-signature-file10.0.1-TT.2-SNAPSHOT</id>
                                <phase>generate-test-sources10.0.1-TT.2-SNAPSHOT</phase>
                                <goals>
                                    <goal>unpack10.0.1-TT.2-SNAPSHOT</goal>
                                10.0.1-TT.2-SNAPSHOT</goals>
                                <configuration>
                                    <artifactItems>
                                        <artifactItem>
                                            <groupId>jakarta.ws.rs10.0.1-TT.2-SNAPSHOT</groupId>
                                            <artifactId>jakarta-restful-ws-tck10.0.1-TT.2-SNAPSHOT</artifactId>
                                            <version>${jaxrs.tck.version}10.0.1-TT.2-SNAPSHOT</version>
                                            <overWrite>true10.0.1-TT.2-SNAPSHOT</overWrite>
                                            <includes>**/jakarta.ws.rs.sig_3.1.010.0.1-TT.2-SNAPSHOT</includes>
                                        10.0.1-TT.2-SNAPSHOT</artifactItem>
                                    10.0.1-TT.2-SNAPSHOT</artifactItems>
                                    <outputDirectory>${project.build.directory}/api-signature10.0.1-TT.2-SNAPSHOT</outputDirectory>
                                10.0.1-TT.2-SNAPSHOT</configuration>
                            10.0.1-TT.2-SNAPSHOT</execution>
                        10.0.1-TT.2-SNAPSHOT</executions>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                    <plugin>
                        <groupId>jakarta.tck10.0.1-TT.2-SNAPSHOT</groupId>
                        <artifactId>sigtest-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
                        <version>2.310.0.1-TT.2-SNAPSHOT</version>
                        <executions>
                            <execution>
                                <id>sigtest10.0.1-TT.2-SNAPSHOT</id>
                                <phase>verify10.0.1-TT.2-SNAPSHOT</phase>
                                <goals>
                                    <goal>check10.0.1-TT.2-SNAPSHOT</goal>
                                10.0.1-TT.2-SNAPSHOT</goals>
                            10.0.1-TT.2-SNAPSHOT</execution>
                        10.0.1-TT.2-SNAPSHOT</executions>
                        <configuration>
                            <sigfile>
                                ${project.build.directory}/api-signature/ee/jakarta/tck/ws/rs/signaturetest/jakarta.ws.rs.sig_3.1.0
                            10.0.1-TT.2-SNAPSHOT</sigfile>
                            <packages>
                                jakarta.ws.rs,jakarta.ws.rs.client,jakarta.ws.rs.container,jakarta.ws.rs.core,jakarta.ws.rs.ext,jakarta.ws.rs.see
                            10.0.1-TT.2-SNAPSHOT</packages>
                        10.0.1-TT.2-SNAPSHOT</configuration>
                    10.0.1-TT.2-SNAPSHOT</plugin>
                10.0.1-TT.2-SNAPSHOT</plugins>
            10.0.1-TT.2-SNAPSHOT</build>
        10.0.1-TT.2-SNAPSHOT</profile>
    10.0.1-TT.2-SNAPSHOT</profiles>
10.0.1-TT.2-SNAPSHOT</project>