<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!-- $Rev: 600338 $ $Date: 2007-12-02 09:08:04 -0800 (Sun, 02 Dec 2007) $ -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <parent>
    <artifactId>tomee10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>

  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <artifactId>tomee-webapp10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>jar10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: TomEE :: Webapp10.0.1-TT.2-SNAPSHOT</name>
  <properties>
    <tomee.build.name>${project.groupId}.tomee.webapp10.0.1-TT.2-SNAPSHOT</tomee.build.name>
    <project.build.sourceEncoding>UTF-810.0.1-TT.2-SNAPSHOT</project.build.sourceEncoding>
  10.0.1-TT.2-SNAPSHOT</properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-dependency-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>unpack10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>unpack10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.webjars10.0.1-TT.2-SNAPSHOT</groupId>
                  <artifactId>bootstrap10.0.1-TT.2-SNAPSHOT</artifactId>
                  <version>3.1.010.0.1-TT.2-SNAPSHOT</version>
                  <includes>**/bootstrap.min.css,**/bootstrap.min.js,**/bootstrap.min.css,**/bootstrap.css.map,**/fonts/*10.0.1-TT.2-SNAPSHOT</includes>
                10.0.1-TT.2-SNAPSHOT</artifactItem>
                <artifactItem>
                  <groupId>org.webjars10.0.1-TT.2-SNAPSHOT</groupId>
                  <artifactId>jquery10.0.1-TT.2-SNAPSHOT</artifactId>
                  <version>2.1.0-110.0.1-TT.2-SNAPSHOT</version>
                  <includes>**/jquery.min.*10.0.1-TT.2-SNAPSHOT</includes>
                10.0.1-TT.2-SNAPSHOT</artifactItem>
              10.0.1-TT.2-SNAPSHOT</artifactItems>
              <outputDirectory>${project.build.directory}/webjars-resources10.0.1-TT.2-SNAPSHOT</outputDirectory>
              <overWriteReleases>false10.0.1-TT.2-SNAPSHOT</overWriteReleases>
              <overWriteSnapshots>true10.0.1-TT.2-SNAPSHOT</overWriteSnapshots>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin> <!-- the jar is only for resources and other classes are for the gui -->
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-jar-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <configuration>
          <includes>
            <include>META-INF/**/*10.0.1-TT.2-SNAPSHOT</include>
            <include>juli.properties10.0.1-TT.2-SNAPSHOT</include>
          10.0.1-TT.2-SNAPSHOT</includes>
          <archive combine.children="append">
            <manifestEntries>
              <Automatic-Module-Name>${tomee.build.name}10.0.1-TT.2-SNAPSHOT</Automatic-Module-Name>
            10.0.1-TT.2-SNAPSHOT</manifestEntries>
          10.0.1-TT.2-SNAPSHOT</archive>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-assembly-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>war10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>attached10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
        <configuration>
          <appendAssemblyId>false10.0.1-TT.2-SNAPSHOT</appendAssemblyId>
          <descriptors>
            <descriptor>src/main/assembly/war.xml10.0.1-TT.2-SNAPSHOT</descriptor>
          10.0.1-TT.2-SNAPSHOT</descriptors>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>com.googlecode.jslint4java10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>jslint4java-maven-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <configuration>
          <failOnError>true10.0.1-TT.2-SNAPSHOT</failOnError>
          <options>
            <vars>true10.0.1-TT.2-SNAPSHOT</vars>
            <predef>$,CodeMirror,Handlebars,define,window,console,requirejs,require,APP_CONFIG10.0.1-TT.2-SNAPSHOT</predef>
            <indent>410.0.1-TT.2-SNAPSHOT</indent>
          10.0.1-TT.2-SNAPSHOT</options>
          <sourceFolders>
            <sourceFolder>${basedir}/src/main/webapp/app/js10.0.1-TT.2-SNAPSHOT</sourceFolder>
          10.0.1-TT.2-SNAPSHOT</sourceFolders>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>

    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>
  <dependencies>
    <dependency>
      <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-pool210.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-dbcp2-shade10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>commons-dbcp210.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.commons10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-lang310.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <classifier>tomcat10.0.1-TT.2-SNAPSHOT</classifier>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-client10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-javaagent10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-jee-accessors10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf-rs10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf-transport10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-cxf10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>jakarta.xml.bind10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakarta.xml.bind-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-ejbd10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-hsql10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-http10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-rest10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-server10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-webservices10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-common10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-jaxrs10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-loader10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion><!-- 'provided' -->
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-mojarra10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-myfaces10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-security10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.geronimo.mail10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>geronimo-mail_2.1_provider10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>runtime10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.johnzon10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>johnzon-core10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>myfaces-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.myfaces}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.geronimo.specs10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>myfaces-impl10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.myfaces}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>myfaces-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.apache.geronimo.specs10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-ee10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-ee-common10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-ejb10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-el2210.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-impl10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-jsf10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-spi10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-web10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-coyote10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>taglibs-shade10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.taglibs10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>taglibs-standard-impl10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.apache.taglibs10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>taglibs-standard-jstlel10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.apache.taglibs10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>taglibs-standard-spec10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>xalan10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>xalan10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>xalan10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>serializer10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openjpa10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openjpa10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.geronimo.components10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>geronimo-transaction10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.geronimo.components10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>geronimo-connector10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openejb.shade10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>quartz-openejb-shade10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.quartz-openejb-shade}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>org.quartz-scheduler10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>quartz10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.tomitribe.quartz10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>quartz10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>jakarta.transaction10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>jta10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>c3p010.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>c3p010.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <groupId>org.slf4j10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>slf4j-api10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.tomitribe10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>swizzle10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.easymock10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>easymock10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>5.5.010.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
  10.0.1-TT.2-SNAPSHOT</dependencies>
  <!--
  Webapp distributions removed per:
    - https://issues.apache.org/jira/browse/TOMEE-3724
    - https://lists.apache.org/thread/31w7336d5ycqhmoy4pngbsjg3odm0yqx
  -->
  <distributionManagement>
    <repository>
      <id>localhost10.0.1-TT.2-SNAPSHOT</id>
      <url>file://${basedir}/target/repo/10.0.1-TT.2-SNAPSHOT</url>
    10.0.1-TT.2-SNAPSHOT</repository>
    <snapshotRepository>
      <id>localhost10.0.1-TT.2-SNAPSHOT</id>
      <url>file://${basedir}/target/snapshot-repo/10.0.1-TT.2-SNAPSHOT</url>
    10.0.1-TT.2-SNAPSHOT</snapshotRepository>
  10.0.1-TT.2-SNAPSHOT</distributionManagement>
10.0.1-TT.2-SNAPSHOT</project>
