<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!-- $Rev: 600338 $ $Date: 2007-12-02 09:08:04 -0800 (Sun, 02 Dec 2007) $ -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <parent>
    <artifactId>tomee10.0.1-TT.2-SNAPSHOT</artifactId>
    <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
    <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>
  10.0.1-TT.2-SNAPSHOT</parent>

  <modelVersion>4.0.010.0.1-TT.2-SNAPSHOT</modelVersion>
  <artifactId>tomee-embedded10.0.1-TT.2-SNAPSHOT</artifactId>
  <packaging>jar10.0.1-TT.2-SNAPSHOT</packaging>
  <name>TomEE :: TomEE :: TomEE Embedded10.0.1-TT.2-SNAPSHOT</name>
  <version>10.0.1-TT.2-SNAPSHOT10.0.1-TT.2-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-jar-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <configuration>
          <archive combine.children="append">
            <manifest>
              <Main-Class>org.apache.tomee.embedded.Main10.0.1-TT.2-SNAPSHOT</Main-Class>
              <!-- the following is not really required if we shade everything together
              Moreover, it generates a lot of stacktraces because Tomcat reads the class-path
              attribute from the manifest and tries to resolve entries based on tomee-embedded
              https://github.com/apache/tomcat/blob/main/java/org/apache/tomcat/util/scan/StandardJarScanner.java#L467

              We end up with things like
              file:/....../.m2/repository/org/apache/tomee/tomee-embedded/10.0.1-TT.1-SNAPSHOT/tomee-config-10.0.1-TT.1-SNAPSHOT.jar
              <addClasspath>true10.0.1-TT.2-SNAPSHOT</addClasspath>
              -->
            10.0.1-TT.2-SNAPSHOT</manifest>
            <manifestEntries>
              <Automatic-Module-Name>${tomee.build.name}10.0.1-TT.2-SNAPSHOT</Automatic-Module-Name>
            10.0.1-TT.2-SNAPSHOT</manifestEntries>
          10.0.1-TT.2-SNAPSHOT</archive>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-shade-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution> <!-- real tomee-embedded (typically webprofile + AMQ) -->
            <id>uber-shade10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>shade10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <shadedClassifierName>uber10.0.1-TT.2-SNAPSHOT</shadedClassifierName>
              <artifactSet>
                <excludes>
                  <exclude>junit:junit10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.junit.jupiter:junit-jupiter-api10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-api10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-impl10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-runtime10.0.1-TT.2-SNAPSHOT</exclude>
                10.0.1-TT.2-SNAPSHOT</excludes>
              10.0.1-TT.2-SNAPSHOT</artifactSet>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
          <execution> <!-- kind of webprofile minus JSF -->
            <id>jaxrs-shade10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>shade10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <shadedClassifierName>jaxrs10.0.1-TT.2-SNAPSHOT</shadedClassifierName>
              <artifactSet>
                <excludes>
                  <exclude>org.junit.jupiter:junit-jupiter-api10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-api10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-impl10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-runtime10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.activemq:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.activemq.protobuf:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.fusesource.hawtbuf:hawtbuf10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.myfaces.core:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <!-- jaxws -->
                  <exclude>joda-time:joda-time10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude> commons-codec:commons-codec10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>${project.groupId}:tomee-webservices10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>${project.groupId}:openejb-webservices10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>${project.groupId}:openejb-cxf10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.wss4j:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.santuario:xmlsec10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.opensaml:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.jasypt:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>net.shibboleth.utilities:java-support10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.cryptacular:cryptacular10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.bouncycastle:bcprov-jdk15to1810.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.neethi:neethi10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-frontend-jaxws10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-bindings-soap10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-bindings-xml10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-frontend-simple10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-wsdl10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-databinding-jaxb10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-ws-addr10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-ws-security10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-ws-policy10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-security-saml10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.ws.xmlschema:xmlschema-core10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>xml-resolver:xml-resolver10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>com.sun.xml.messaging.saaj:saaj-impl10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.jvnet.mimepull:mimepull10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>wsdl4j:wsdl4j10.0.1-TT.2-SNAPSHOT</exclude>
                10.0.1-TT.2-SNAPSHOT</excludes>
              10.0.1-TT.2-SNAPSHOT</artifactSet>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
          <execution> <!-- kind of webprofile plus JAX-WS minus JSF -->
            <id>jaxws-shade10.0.1-TT.2-SNAPSHOT</id>
            <phase>package10.0.1-TT.2-SNAPSHOT</phase>
            <goals>
              <goal>shade10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <shadedClassifierName>jaxws10.0.1-TT.2-SNAPSHOT</shadedClassifierName>
              <artifactSet>
                <excludes>
                  <exclude>junit:junit10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.junit.jupiter:junit-jupiter-api10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-api10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-impl10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>*:jaxb-runtime10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.activemq:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.activemq.protobuf:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.fusesource.hawtbuf:hawtbuf10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.myfaces.core:*10.0.1-TT.2-SNAPSHOT</exclude>
                  <!-- jaxrs -->
                  <exclude>${project.groupId}:tomee-jaxrs10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>${project.groupId}:openejb-rest10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>${project.groupId}:openejb-cxf-rs10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-service-description10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-client10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-frontend-jaxrs10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-extension-search10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-json-basic10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-security-cors10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-security-oauth210.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-security-jose-jaxrs10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-security-jose10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.cxf:cxf-rt-rs-extension-providers10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.johnzon:johnzon-jaxrs10.0.1-TT.2-SNAPSHOT</exclude>
                  <exclude>org.apache.johnzon:johnzon-mapper10.0.1-TT.2-SNAPSHOT</exclude>
                10.0.1-TT.2-SNAPSHOT</excludes>
              10.0.1-TT.2-SNAPSHOT</artifactSet>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
        <configuration>
          <useBaseVersion>true10.0.1-TT.2-SNAPSHOT</useBaseVersion>
          <createDependencyReducedPom>false10.0.1-TT.2-SNAPSHOT</createDependencyReducedPom>
          <shadedArtifactAttached>true10.0.1-TT.2-SNAPSHOT</shadedArtifactAttached>
          <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
              <mainClass>org.apache.tomee.embedded.Main10.0.1-TT.2-SNAPSHOT</mainClass>
            10.0.1-TT.2-SNAPSHOT</transformer>
            <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
              <resource>META-INF/cxf/bus-extensions.txt10.0.1-TT.2-SNAPSHOT</resource>
            10.0.1-TT.2-SNAPSHOT</transformer>
            <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
              <resource>META-INF/openwebbeans/openwebbeans.properties10.0.1-TT.2-SNAPSHOT</resource>
            10.0.1-TT.2-SNAPSHOT</transformer>
          10.0.1-TT.2-SNAPSHOT</transformers>
          <filters>
            <filter>
              <artifact>*:*10.0.1-TT.2-SNAPSHOT</artifact>
              <excludes>
                <exclude>META-INF/ejb-jar.xml10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>META-INF/openejb-jar.xml10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>META-INF/web-fragment.xml10.0.1-TT.2-SNAPSHOT</exclude>
                <!--
                NOTE:
                we shouldn't exclude faces-config.xml while we didn't impl the feature in another manner
                but it breaks all apps not using JSF.
                Solution would be to handle it more deeply in our myfaces integration
                -->
                <exclude>META-INF/faces-config.xml10.0.1-TT.2-SNAPSHOT</exclude>

                <!-- to avoid to not be able to run the shade -->
                <exclude>META-INF/*.SF10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>META-INF/*.DSA10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>META-INF/*.RSA10.0.1-TT.2-SNAPSHOT</exclude>
              10.0.1-TT.2-SNAPSHOT</excludes>
            10.0.1-TT.2-SNAPSHOT</filter>
          10.0.1-TT.2-SNAPSHOT</filters>
        10.0.1-TT.2-SNAPSHOT</configuration>
      10.0.1-TT.2-SNAPSHOT</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins10.0.1-TT.2-SNAPSHOT</groupId>
        <artifactId>maven-surefire-plugin10.0.1-TT.2-SNAPSHOT</artifactId>
        <executions>
          <execution>
            <id>default-test10.0.1-TT.2-SNAPSHOT</id>
            <goals>
              <goal>test10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <excludes>
                <exclude>**/SingleInstanceRunnerTest*10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>**/SingleInstanceRunnerExtensionTest*10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>**/NoScannerSingleRunnerTest*10.0.1-TT.2-SNAPSHOT</exclude>
                <exclude>**/NoScannerSingleRunnerExtensionTest*10.0.1-TT.2-SNAPSHOT</exclude>
              10.0.1-TT.2-SNAPSHOT</excludes>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
          <execution>
            <id>single-server-default-scanning10.0.1-TT.2-SNAPSHOT</id>
            <goals>
              <goal>test10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <includes>
                <include>**/SingleInstanceRunnerTest*10.0.1-TT.2-SNAPSHOT</include>
              10.0.1-TT.2-SNAPSHOT</includes>
              <systemPropertyVariables>
                <tomee.application-composer.application>org.apache.tomee.embedded.SingleInstanceRunnerTest$TheApp10.0.1-TT.2-SNAPSHOT</tomee.application-composer.application>
              10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
          <execution>
            <id>single-server-custom-scanning10.0.1-TT.2-SNAPSHOT</id>
            <goals>
              <goal>test10.0.1-TT.2-SNAPSHOT</goal>
            10.0.1-TT.2-SNAPSHOT</goals>
            <configuration>
              <includes>
                <include>**/NoScannerSingleRunnerTest*10.0.1-TT.2-SNAPSHOT</include>
              10.0.1-TT.2-SNAPSHOT</includes>
              <systemPropertyVariables>
                <tomee.application-composer.application>org.apache.tomee.embedded.NoScannerSingleRunnerTest$ScanApp10.0.1-TT.2-SNAPSHOT</tomee.application-composer.application>
              10.0.1-TT.2-SNAPSHOT</systemPropertyVariables>
            10.0.1-TT.2-SNAPSHOT</configuration>
          10.0.1-TT.2-SNAPSHOT</execution>
        10.0.1-TT.2-SNAPSHOT</executions>
      10.0.1-TT.2-SNAPSHOT</plugin>
    10.0.1-TT.2-SNAPSHOT</plugins>
  10.0.1-TT.2-SNAPSHOT</build>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>tomcat-annotations-api10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-util10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>myfaces-api10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <classifier>tomcat10.0.1-TT.2-SNAPSHOT</classifier>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-websocket-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-websocket-client-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-myfaces10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-core10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <artifactId>commons-beautils-core10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>commons-beautils10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.openwebbeans10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openwebbeans-jsf10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <!-- we already have jakarta version coming from core. We don't want non jakarta version transitively -->
      <exclusions>
        <exclusion>
          <groupId>*10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.myfaces.core10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>myfaces-impl10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomee10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>taglibs-shade10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>*10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>*10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-jdbc10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-dbcp10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-catalina10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-annotations-api10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>

    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-catalina-ha10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-coyote10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-jasper10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
      <exclusions>
        <exclusion>
          <groupId>org.eclipse.jdt10.0.1-TT.2-SNAPSHOT</groupId>
          <artifactId>ecj10.0.1-TT.2-SNAPSHOT</artifactId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-jasper-el10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>junit10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.junit.jupiter10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit-jupiter-api10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>provided10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.junit.jupiter10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit-jupiter-engine10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <!-- Required for running JUnit 4 via JUnit 5 environment -->
    <dependency>
      <groupId>org.junit.vintage10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>junit-vintage-engine10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.eclipse.jdt10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>ecj10.0.1-TT.2-SNAPSHOT</artifactId>
      <type>jar10.0.1-TT.2-SNAPSHOT</type>
      <scope>compile10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.velocity10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>velocity-engine-core10.0.1-TT.2-SNAPSHOT</artifactId>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>openejb-client10.0.1-TT.2-SNAPSHOT</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>jakartaee-api10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency> <!-- now in webprofile -->
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-jaxrs10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>${project.groupId}10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomee-webservices10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${project.version}10.0.1-TT.2-SNAPSHOT</version>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>tomcat-websocket10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${tomcat.version}10.0.1-TT.2-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <artifactId>tomcat-juli10.0.1-TT.2-SNAPSHOT</artifactId>
          <groupId>org.apache.tomcat10.0.1-TT.2-SNAPSHOT</groupId>
        10.0.1-TT.2-SNAPSHOT</exclusion>
      10.0.1-TT.2-SNAPSHOT</exclusions>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>commons-io10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>commons-io10.0.1-TT.2-SNAPSHOT</artifactId>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>shrinkwrap-impl-base10.0.1-TT.2-SNAPSHOT</artifactId>
      <version>${version.shrinkwrap.shrinkwrap}10.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>
    <dependency>
      <groupId>org.bouncycastle10.0.1-TT.2-SNAPSHOT</groupId>
      <artifactId>bcmail-jdk15to1810.0.1-TT.2-SNAPSHOT</artifactId>
      <version>1.8010.0.1-TT.2-SNAPSHOT</version>
      <scope>test10.0.1-TT.2-SNAPSHOT</scope>
    10.0.1-TT.2-SNAPSHOT</dependency>

  10.0.1-TT.2-SNAPSHOT</dependencies>
10.0.1-TT.2-SNAPSHOT</project>
